//! TypeScript client codegen from a parsed [`Schema`].
//!
//! Given a [`Schema`] (models + actions), [`generate_typescript_client`] emits a
//! self-contained TypeScript module containing:
//!
//! * **Model interfaces** — one `export interface` per model with correctly typed fields.
//! * **Action input types** — `Pick<Model, ...>` types for `PickFields` inputs, inline
//!   object types for `Object` inputs.
//! * **Typed CRUD client** — a wrapper class (`TypedClient`) with a property per model
//!   exposing `create`, `findById`, `update`, `delete`, and `findMany` methods that
//!   delegate to an untyped `CrudClient`.
//! * **Event type map** — a `ModelEventMap` type that maps `"Model.created"` etc. to the
//!   action names that fire, so workers can see which events trigger what.
//! * **Typed worker** — `ActionHandlers` map, `TypedJobContext<K>`, and `TypedWorker`
//!   interface so `worker.on("processPost", ctx => ...)` narrows `ctx.job.payload.input`
//!   to the action's declared input type.
//!
//! The output is deterministic: models and actions are sorted alphabetically so the same
//! schema always produces the same file.

use crate::types::{ActionInputDef, FieldType, Schema};

/// Map a schema [`FieldType`] to its TypeScript equivalent.
fn ts_type(ft: &FieldType) -> String {
    match ft {
        FieldType::String | FieldType::EntityId | FieldType::File => "string".to_string(),
        FieldType::Number => "number".to_string(),
        FieldType::Boolean => "boolean".to_string(),
        FieldType::Date | FieldType::DateTime => "string".to_string(),
        FieldType::Json | FieldType::Blocks | FieldType::Custom(_) => "unknown".to_string(),
        FieldType::Reference(_) => "string".to_string(),
        FieldType::Array(inner) => format!("{}[]", ts_type(inner)),
    }
}

/// Generate a complete TypeScript client module from a parsed schema.
///
/// The returned string is valid TypeScript that can be written to a `.ts` file and
/// imported by worker code. It assumes a `CrudClient` type exists at import time with
/// the standard untyped CRUD surface (`create(model, data)`, etc.).
pub fn generate_typescript_client(schema: &Schema) -> String {
    let mut out = String::new();

    // -- Preamble / untyped client interface ------------------------------------
    out.push_str("// Auto-generated by atomo codegen — do not edit.\n\n");
    out.push_str(
        "export interface CrudClient {\n\
         \x20 create(model: string, data: Record<string, unknown>): Promise<Record<string, unknown>>;\n\
         \x20 findById(model: string, id: string): Promise<Record<string, unknown> | null>;\n\
         \x20 update(model: string, id: string, data: Record<string, unknown>): Promise<Record<string, unknown>>;\n\
         \x20 delete(model: string, id: string): Promise<void>;\n\
         \x20 findMany(model: string, opts?: Record<string, unknown>): Promise<Record<string, unknown>[]>;\n\
         }\n\n",
    );

    // Sort models for deterministic output.
    let mut model_names: Vec<&String> = schema.models.keys().collect();
    model_names.sort();

    // -- Model interfaces -------------------------------------------------------
    for name in &model_names {
        let model = &schema.models[*name];
        out.push_str(&format!("export interface {} {{\n", name));

        let mut field_names: Vec<&String> = model.fields.keys().collect();
        field_names.sort();
        for fname in &field_names {
            let field = &model.fields[*fname];
            let opt = if field.optional { "?" } else { "" };
            out.push_str(&format!(
                "  {}{}: {};\n",
                fname,
                opt,
                ts_type(&field.field_type)
            ));
        }
        out.push_str("}\n\n");
    }

    // -- Action input types -----------------------------------------------------
    let mut action_names: Vec<&String> = schema.actions.keys().collect();
    action_names.sort();

    for aname in &action_names {
        let action = &schema.actions[*aname];
        match &action.input {
            ActionInputDef::PickFields { model, fields } => {
                let fields_str = fields
                    .iter()
                    .map(|f| format!("'{}'", f))
                    .collect::<Vec<_>>()
                    .join(" | ");
                out.push_str(&format!(
                    "export type {}Input = Pick<{}, {}>;\n\n",
                    aname, model, fields_str
                ));
            }
            ActionInputDef::Object { fields } => {
                out.push_str(&format!("export interface {}Input {{\n", aname));
                for f in fields {
                    let opt = if f.required { "" } else { "?" };
                    out.push_str(&format!("  {}{}: {};\n", f.name, opt, f.field_type));
                }
                out.push_str("}\n\n");
            }
        }
    }

    // -- Per-model CRUD helper types --------------------------------------------
    for name in &model_names {
        out.push_str(&format!(
            "export interface {name}Crud {{\n\
             \x20 create(data: Partial<{name}>): Promise<{name}>;\n\
             \x20 findById(id: string): Promise<{name} | null>;\n\
             \x20 update(id: string, data: Partial<{name}>): Promise<{name}>;\n\
             \x20 delete(id: string): Promise<void>;\n\
             \x20 findMany(opts?: Record<string, unknown>): Promise<{name}[]>;\n\
             }}\n\n"
        ));
    }

    // -- TypedClient class ------------------------------------------------------
    out.push_str("export class TypedClient {\n");
    out.push_str("  constructor(private client: CrudClient) {}\n\n");

    for name in &model_names {
        // Property name: lowercase first letter of the model name.
        let prop = lowercase_first(name);
        out.push_str(&format!(
            "  {prop}: {name}Crud = {{\n\
             \x20\x20\x20 create: (data) => this.client.create('{name}', data as Record<string, unknown>) as Promise<{name}>,\n\
             \x20\x20\x20 findById: (id) => this.client.findById('{name}', id) as Promise<{name} | null>,\n\
             \x20\x20\x20 update: (id, data) => this.client.update('{name}', id, data as Record<string, unknown>) as Promise<{name}>,\n\
             \x20\x20\x20 delete: (id) => this.client.delete('{name}', id),\n\
             \x20\x20\x20 findMany: (opts) => this.client.findMany('{name}', opts) as Promise<{name}[]>,\n\
             \x20 }};\n\n"
        ));
    }

    out.push_str("}\n\n");

    // -- Event type map ---------------------------------------------------------
    out.push_str("export interface ModelEventMap {\n");
    for name in &model_names {
        let model = &schema.models[*name];
        let events = &model.events;
        for (event_kind, bindings) in [
            ("created", &events.created),
            ("updated", &events.updated),
            ("deleted", &events.deleted),
        ] {
            if bindings.is_empty() {
                continue;
            }
            let actions_str = bindings
                .iter()
                .map(|b| format!("'{}'", b.action))
                .collect::<Vec<_>>()
                .join(" | ");
            out.push_str(&format!(
                "  '{}.{}': {};\n",
                name, event_kind, actions_str
            ));
        }
    }
    out.push_str("}\n");

    // -- Typed worker support --------------------------------------------------
    if !action_names.is_empty() {
        out.push_str("\nexport interface ActionHandlers {\n");
        for aname in &action_names {
            out.push_str(&format!(
                "  {}: {{ input: {}Input }};\n",
                aname, aname
            ));
        }
        out.push_str("}\n\n");

        out.push_str(
            "export interface TypedJobContext<K extends keyof ActionHandlers> {\n  \
             job: {\n    \
             id: string;\n    \
             queue: string;\n    \
             kind: K;\n    \
             payload: { input: ActionHandlers[K]['input']; [key: string]: unknown };\n    \
             attempts: number;\n    \
             maxAttempts: number;\n    \
             leaseId: string;\n  \
             };\n  \
             signal: AbortSignal;\n  \
             heartbeat(): Promise<void>;\n  \
             progress(update: { percent?: number; message?: string; data?: unknown }): Promise<void>;\n  \
             crud: TypedClient;\n\
             }\n\n",
        );

        out.push_str(
            "export interface TypedWorker {\n  \
             on<K extends keyof ActionHandlers>(\n    \
             kind: K,\n    \
             handler: (ctx: TypedJobContext<K>) => Promise<unknown> | unknown,\n  \
             ): TypedWorker;\n  \
             start(): void;\n  \
             stop(): Promise<void>;\n\
             }\n",
        );
    }

    out
}

/// Lowercase the first character of a string (for property names like `post` from `Post`).
fn lowercase_first(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => c.to_lowercase().collect::<String>() + chars.as_str(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{
        ActionDef, ActionInputDef, ActionInputField, EventActionBinding, Field, FieldType, Model,
        ModelEvents, Schema,
    };
    use std::collections::HashMap;

    /// Helper to create a field tuple for insertion into a model's field map.
    fn field(name: &str, ty: FieldType, optional: bool) -> (String, Field) {
        (
            name.to_string(),
            Field {
                name: name.to_string(),
                field_type: ty,
                optional,
                attributes: vec![],
            },
        )
    }

    /// Helper to build a minimal model with the given fields and events.
    fn model(name: &str, fields: Vec<(String, Field)>, events: ModelEvents) -> Model {
        Model {
            name: name.to_string(),
            fields: fields.into_iter().collect(),
            access: None,
            hooks: None,
            validation: HashMap::new(),
            table_name: None,
            relationships: HashMap::new(),
            constraints: Vec::new(),
            events,
        }
    }

    fn empty_events() -> ModelEvents {
        ModelEvents::default()
    }

    #[test]
    fn model_interfaces_have_correct_field_types() {
        let post = model(
            "Post",
            vec![
                field("id", FieldType::EntityId, false),
                field("title", FieldType::String, false),
                field("views", FieldType::Number, false),
                field("published", FieldType::Boolean, false),
                field("createdAt", FieldType::DateTime, false),
                field("tags", FieldType::Array(Box::new(FieldType::String)), false),
                field("meta", FieldType::Json, false),
            ],
            empty_events(),
        );

        let mut models = HashMap::new();
        models.insert("Post".to_string(), post);
        let schema = Schema {
            models,
            actions: HashMap::new(),
        };

        let ts = generate_typescript_client(&schema);

        assert!(ts.contains("export interface Post {"), "interface missing");
        assert!(ts.contains("id: string;"), "EntityId -> string");
        assert!(ts.contains("title: string;"), "String -> string");
        assert!(ts.contains("views: number;"), "Number -> number");
        assert!(ts.contains("published: boolean;"), "Boolean -> boolean");
        assert!(ts.contains("createdAt: string;"), "DateTime -> string");
        assert!(ts.contains("tags: string[];"), "Array(String) -> string[]");
        assert!(ts.contains("meta: unknown;"), "Json -> unknown");
    }

    #[test]
    fn optional_fields_get_question_mark() {
        let post = model(
            "Post",
            vec![
                field("id", FieldType::EntityId, false),
                field("subtitle", FieldType::String, true),
            ],
            empty_events(),
        );

        let mut models = HashMap::new();
        models.insert("Post".to_string(), post);
        let schema = Schema {
            models,
            actions: HashMap::new(),
        };

        let ts = generate_typescript_client(&schema);

        assert!(ts.contains("id: string;"), "required field has no ?");
        assert!(
            ts.contains("subtitle?: string;"),
            "optional field should have ?"
        );
    }

    #[test]
    fn action_pick_fields_input_type() {
        let post = model(
            "Post",
            vec![
                field("id", FieldType::EntityId, false),
                field("title", FieldType::String, false),
                field("body", FieldType::String, false),
            ],
            empty_events(),
        );

        let mut actions = HashMap::new();
        actions.insert(
            "ProcessPost".to_string(),
            ActionDef {
                name: "ProcessPost".to_string(),
                input: ActionInputDef::PickFields {
                    model: "Post".to_string(),
                    fields: vec!["id".to_string(), "title".to_string()],
                },
                returns: None,
                source_model: Some("Post".to_string()),
            },
        );

        let mut models = HashMap::new();
        models.insert("Post".to_string(), post);
        let schema = Schema { models, actions };

        let ts = generate_typescript_client(&schema);

        assert!(
            ts.contains("export type ProcessPostInput = Pick<Post, 'id' | 'title'>;"),
            "Pick type not found in output:\n{}",
            ts
        );
    }

    #[test]
    fn action_object_input_type() {
        let mut actions = HashMap::new();
        actions.insert(
            "SendEmail".to_string(),
            ActionDef {
                name: "SendEmail".to_string(),
                input: ActionInputDef::Object {
                    fields: vec![
                        ActionInputField {
                            name: "to".to_string(),
                            field_type: "string".to_string(),
                            required: true,
                        },
                        ActionInputField {
                            name: "subject".to_string(),
                            field_type: "string".to_string(),
                            required: true,
                        },
                        ActionInputField {
                            name: "cc".to_string(),
                            field_type: "string".to_string(),
                            required: false,
                        },
                    ],
                },
                returns: None,
                source_model: None,
            },
        );

        let schema = Schema {
            models: HashMap::new(),
            actions,
        };

        let ts = generate_typescript_client(&schema);

        assert!(ts.contains("export interface SendEmailInput {"), "Object input interface missing");
        assert!(ts.contains("to: string;"), "required field missing");
        assert!(ts.contains("cc?: string;"), "optional field missing ?");
    }

    #[test]
    fn typed_crud_methods_generated_per_model() {
        let post = model(
            "Post",
            vec![field("id", FieldType::EntityId, false)],
            empty_events(),
        );
        let comment = model(
            "Comment",
            vec![field("id", FieldType::EntityId, false)],
            empty_events(),
        );

        let mut models = HashMap::new();
        models.insert("Post".to_string(), post);
        models.insert("Comment".to_string(), comment);
        let schema = Schema {
            models,
            actions: HashMap::new(),
        };

        let ts = generate_typescript_client(&schema);

        // TypedClient class exists
        assert!(
            ts.contains("export class TypedClient"),
            "TypedClient class missing"
        );

        // Post CRUD property
        assert!(ts.contains("post: PostCrud"), "post property missing");
        assert!(
            ts.contains("this.client.create('Post'"),
            "Post create delegation missing"
        );
        assert!(
            ts.contains("this.client.findById('Post'"),
            "Post findById delegation missing"
        );
        assert!(
            ts.contains("this.client.update('Post'"),
            "Post update delegation missing"
        );
        assert!(
            ts.contains("this.client.delete('Post'"),
            "Post delete delegation missing"
        );
        assert!(
            ts.contains("this.client.findMany('Post'"),
            "Post findMany delegation missing"
        );

        // Comment CRUD property
        assert!(
            ts.contains("comment: CommentCrud"),
            "comment property missing"
        );
        assert!(
            ts.contains("this.client.create('Comment'"),
            "Comment create delegation missing"
        );
    }

    #[test]
    fn empty_schema_produces_minimal_output() {
        let schema = Schema {
            models: HashMap::new(),
            actions: HashMap::new(),
        };

        let ts = generate_typescript_client(&schema);

        // Should still have preamble and the (empty) class/event map.
        assert!(ts.contains("Auto-generated"), "preamble missing");
        assert!(
            ts.contains("export class TypedClient"),
            "TypedClient should still be emitted"
        );
        assert!(
            ts.contains("export interface ModelEventMap"),
            "ModelEventMap should still be emitted"
        );
        // No model interfaces.
        assert!(
            !ts.contains("export interface Post"),
            "no models means no model interfaces"
        );
    }

    #[test]
    fn event_type_map_generated() {
        let events = ModelEvents {
            created: vec![EventActionBinding {
                action: "IndexPost".to_string(),
                condition: None,
            }],
            updated: vec![
                EventActionBinding {
                    action: "ReindexPost".to_string(),
                    condition: None,
                },
                EventActionBinding {
                    action: "NotifyAuthor".to_string(),
                    condition: None,
                },
            ],
            deleted: vec![],
        };

        let post = model(
            "Post",
            vec![field("id", FieldType::EntityId, false)],
            events,
        );

        let mut models = HashMap::new();
        models.insert("Post".to_string(), post);
        let schema = Schema {
            models,
            actions: HashMap::new(),
        };

        let ts = generate_typescript_client(&schema);

        assert!(
            ts.contains("'Post.created': 'IndexPost';"),
            "created event mapping missing:\n{}",
            ts
        );
        assert!(
            ts.contains("'Post.updated': 'ReindexPost' | 'NotifyAuthor';"),
            "updated event mapping missing:\n{}",
            ts
        );
        // deleted has no bindings, so should not appear.
        assert!(
            !ts.contains("Post.deleted"),
            "empty deleted should be omitted"
        );
    }

    #[test]
    fn output_is_deterministic_regardless_of_insertion_order() {
        let a = model(
            "Alpha",
            vec![field("id", FieldType::EntityId, false)],
            empty_events(),
        );
        let b = model(
            "Beta",
            vec![field("id", FieldType::EntityId, false)],
            empty_events(),
        );

        // Insert in reverse order.
        let mut models = HashMap::new();
        models.insert("Beta".to_string(), b.clone());
        models.insert("Alpha".to_string(), a.clone());
        let ts1 = generate_typescript_client(&Schema {
            models,
            actions: HashMap::new(),
        });

        // Insert in forward order.
        let mut models2 = HashMap::new();
        models2.insert("Alpha".to_string(), a);
        models2.insert("Beta".to_string(), b);
        let ts2 = generate_typescript_client(&Schema {
            models: models2,
            actions: HashMap::new(),
        });

        assert_eq!(ts1, ts2, "output should be identical regardless of HashMap order");
    }

    #[test]
    fn action_handlers_and_typed_worker_generated() {
        let post = model(
            "Post",
            vec![
                field("id", FieldType::EntityId, false),
                field("title", FieldType::String, false),
                field("status", FieldType::String, false),
            ],
            empty_events(),
        );

        let mut actions = HashMap::new();
        actions.insert(
            "processPost".to_string(),
            ActionDef {
                name: "processPost".to_string(),
                input: ActionInputDef::PickFields {
                    model: "Post".to_string(),
                    fields: vec!["id".to_string(), "title".to_string()],
                },
                returns: None,
                source_model: Some("Post".to_string()),
            },
        );
        actions.insert(
            "onStatusChange".to_string(),
            ActionDef {
                name: "onStatusChange".to_string(),
                input: ActionInputDef::PickFields {
                    model: "Post".to_string(),
                    fields: vec!["id".to_string(), "status".to_string()],
                },
                returns: None,
                source_model: Some("Post".to_string()),
            },
        );

        let mut models = HashMap::new();
        models.insert("Post".to_string(), post);
        let schema = Schema { models, actions };
        let ts = generate_typescript_client(&schema);

        assert!(
            ts.contains("export interface ActionHandlers {"),
            "ActionHandlers missing:\n{}",
            ts
        );
        assert!(
            ts.contains("processPost: { input: processPostInput };"),
            "processPost handler entry missing:\n{}",
            ts
        );
        assert!(
            ts.contains("onStatusChange: { input: onStatusChangeInput };"),
            "onStatusChange handler entry missing:\n{}",
            ts
        );
        assert!(
            ts.contains("export interface TypedJobContext<K extends keyof ActionHandlers>"),
            "TypedJobContext missing:\n{}",
            ts
        );
        assert!(
            ts.contains("payload: { input: ActionHandlers[K]['input']"),
            "typed payload missing:\n{}",
            ts
        );
        assert!(
            ts.contains("crud: TypedClient;"),
            "typed crud on context missing:\n{}",
            ts
        );
        assert!(
            ts.contains("export interface TypedWorker {"),
            "TypedWorker missing:\n{}",
            ts
        );
        assert!(
            ts.contains("on<K extends keyof ActionHandlers>"),
            "typed on() method missing:\n{}",
            ts
        );
    }

    #[test]
    fn no_actions_skips_worker_types() {
        let post = model(
            "Post",
            vec![field("id", FieldType::EntityId, false)],
            empty_events(),
        );
        let mut models = HashMap::new();
        models.insert("Post".to_string(), post);
        let schema = Schema {
            models,
            actions: HashMap::new(),
        };
        let ts = generate_typescript_client(&schema);

        assert!(
            !ts.contains("ActionHandlers"),
            "ActionHandlers should not appear when no actions"
        );
        assert!(
            !ts.contains("TypedWorker"),
            "TypedWorker should not appear when no actions"
        );
    }

    #[test]
    fn all_field_types_map_correctly() {
        assert_eq!(ts_type(&FieldType::String), "string");
        assert_eq!(ts_type(&FieldType::EntityId), "string");
        assert_eq!(ts_type(&FieldType::File), "string");
        assert_eq!(ts_type(&FieldType::Number), "number");
        assert_eq!(ts_type(&FieldType::Boolean), "boolean");
        assert_eq!(ts_type(&FieldType::Date), "string");
        assert_eq!(ts_type(&FieldType::DateTime), "string");
        assert_eq!(ts_type(&FieldType::Json), "unknown");
        assert_eq!(ts_type(&FieldType::Blocks), "unknown");
        assert_eq!(ts_type(&FieldType::Custom("Foo".to_string())), "unknown");
        assert_eq!(
            ts_type(&FieldType::Reference("User".to_string())),
            "string"
        );
        assert_eq!(
            ts_type(&FieldType::Array(Box::new(FieldType::Number))),
            "number[]"
        );
        assert_eq!(
            ts_type(&FieldType::Array(Box::new(FieldType::Array(Box::new(
                FieldType::String
            ))))),
            "string[][]"
        );
    }
}
