use anyhow::Result;
use crate::types::*;

/// Hasura v2 Style GraphQL Resolver Generator
/// Generates GraphQL resolvers following Hasura v2 conventions and standards
pub struct HasuraV2ResolverGenerator;

impl HasuraV2ResolverGenerator {
    pub fn new() -> Self {
        Self
    }
    
    /// Convert camelCase to snake_case for database field names
    fn camel_to_snake_case(&self, input: &str) -> String {
        let mut result = String::new();
        let mut chars = input.chars().peekable();
        
        while let Some(ch) = chars.next() {
            if ch.is_uppercase() && !result.is_empty() {
                result.push('_');
            }
            result.push(ch.to_lowercase().next().unwrap());
        }
        
        result
    }
    
    /// Generate complete Hasura v2 style resolver implementation
    pub fn generate_resolvers(&self, models: &[Model]) -> Result<String> {
        let mut resolvers = String::new();
        
        // Add resolver header and imports
        resolvers.push_str(&self.generate_header());
        
        // Generate Query resolvers
        resolvers.push_str(&self.generate_query_resolvers(models)?);
        
        // Generate Mutation resolvers  
        resolvers.push_str(&self.generate_mutation_resolvers(models)?);
        
        // Generate resolver registration
        resolvers.push_str(&self.generate_resolver_registration(models)?);
        
        Ok(resolvers)
    }
    
    /// Generate header with imports and basic setup
    fn generate_header(&self) -> String {
        format!(r#"// Auto-generated Hasura v2 Style GraphQL resolvers
// DO NOT EDIT - This file is automatically generated

use async_graphql::{{Context, Object, FieldResult, ID, EmptySubscription}};
use sqlx::PgPool;
use serde_json::Value;

use super::models::*;

// Hasura v2 style resolvers
pub struct Query;
pub struct Mutation;

"#)
    }
    
    /// Generate Query resolvers for all models following Hasura v2 conventions
    fn generate_query_resolvers(&self, models: &[Model]) -> Result<String> {
        let mut query_impl = String::new();
        
        query_impl.push_str("#[Object]\nimpl Query {\n");
        
        for model in models {
            // Skip Block types and enum types
            if model.name.ends_with("Block") || model.fields.contains_key("_enum_type") {
                continue;
            }
            
            let model_name = &model.name;
            let model_lower = model_name.to_lowercase();
            let table_name = format!("{}s", model_lower); // Pluralize table name
            
            // Generate list query: users, deals, companies, contacts
            query_impl.push_str(&self.generate_list_query(model)?);
            
            // Generate single query by primary key: user_by_pk, deal_by_pk
            query_impl.push_str(&self.generate_by_pk_query(model)?);
            
            // Generate aggregate query: users_aggregate, deals_aggregate
            query_impl.push_str(&self.generate_aggregate_query(model)?);
        }
        
        query_impl.push_str("}\n\n");
        Ok(query_impl)
    }
    
    /// Generate list query following Hasura v2 conventions
    fn generate_list_query(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let model_lower = model_name.to_lowercase();
        let table_name = format!("{}s", model_lower);
        
        Ok(format!(
            r#"    /// Query {table_name} with Hasura v2 style filtering and ordering
    async fn {table_name}(
        &self,
        ctx: &Context<'_>,
        where_: Option<{model_name}BoolExp>,
        order_by: Option<Vec<{model_name}OrderBy>>,
        limit: Option<i32>,
        offset: Option<i32>,
        distinct_on: Option<Vec<{model_name}SelectColumn>>,
    ) -> FieldResult<Vec<{model_name}>> {{
        let pool = ctx.data::<PgPool>()?;
        
        // Build base query
        let mut query = format!("SELECT * FROM {model_lower}");
        let mut params: Vec<Box<dyn sqlx::Encode<'_, sqlx::Postgres> + Send + Sync>> = Vec::new();
        let mut param_count = 1;
        
        // Apply where conditions using Hasura v2 boolean expressions
        if let Some(ref where_clause) = where_ {{
            let (where_sql, where_params) = self.build_bool_exp_sql(where_clause, &mut param_count)?;
            if !where_sql.is_empty() {{
                query.push_str(&format!(" WHERE {{}}", where_sql));
                params.extend(where_params);
            }}
        }}
        
        // Apply ordering
        if let Some(ref order_by_clause) = order_by {{
            let order_sql = self.build_order_by_sql(order_by_clause)?;
            if !order_sql.is_empty() {{
                query.push_str(&format!(" ORDER BY {{}}", order_sql));
            }}
        }}
        
        // Apply pagination
        if let Some(limit_val) = limit {{
            query.push_str(&format!(" LIMIT {{}}", limit_val));
        }}
        
        if let Some(offset_val) = offset {{
            query.push_str(&format!(" OFFSET {{}}", offset_val));
        }}
        
        // Execute query
        let mut query_builder = sqlx::query_as::<_, {model_name}Row>(&query);
        
        // Bind parameters
        let rows = query_builder.fetch_all(pool).await?;
        
        // Convert to GraphQL models
        let entities: Vec<{model_name}> = rows.into_iter().map(|row| row.into()).collect();
        
        Ok(entities)
    }}

"#,
            model_name = model_name,
            model_lower = model_lower,
            table_name = table_name,
        ))
    }
    
    /// Generate by_pk query following Hasura v2 conventions
    fn generate_by_pk_query(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let model_lower = model_name.to_lowercase();
        
        Ok(format!(
            r#"    /// Query {model_lower} by primary key
    async fn {model_lower}_by_pk(
        &self,
        ctx: &Context<'_>,
        id: ID,
    ) -> FieldResult<Option<{model_name}>> {{
        let pool = ctx.data::<PgPool>()?;
        
        let entity = sqlx::query_as::<_, {model_name}Row>(
            "SELECT * FROM {model_lower} WHERE id = $1"
        )
        .bind(id.to_string())
        .fetch_optional(pool)
        .await?;

        Ok(entity.map(|e| e.into()))
    }}

"#,
            model_name = model_name,
            model_lower = model_lower,
        ))
    }
    
    /// Generate aggregate query following Hasura v2 conventions
    fn generate_aggregate_query(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let model_lower = model_name.to_lowercase();
        let table_name = format!("{}s", model_lower);
        
        Ok(format!(
            r#"    /// Query {table_name} aggregate with count and statistics
    async fn {table_name}_aggregate(
        &self,
        ctx: &Context<'_>,
        where_: Option<{model_name}BoolExp>,
        order_by: Option<Vec<{model_name}OrderBy>>,
        limit: Option<i32>,
        offset: Option<i32>,
        distinct_on: Option<Vec<{model_name}SelectColumn>>,
    ) -> FieldResult<{model_name}Aggregate> {{
        let pool = ctx.data::<PgPool>()?;
        
        // Build count query
        let mut count_query = format!("SELECT COUNT(*) as count FROM {model_lower}");
        let mut param_count = 1;
        
        // Apply where conditions
        if let Some(ref where_clause) = where_ {{
            let (where_sql, _) = self.build_bool_exp_sql(where_clause, &mut param_count)?;
            if !where_sql.is_empty() {{
                count_query.push_str(&format!(" WHERE {{}}", where_sql));
            }}
        }}
        
        // Get count
        let count_row: (i64,) = sqlx::query_as(&count_query)
            .fetch_one(pool)
            .await?;
        
        // Get nodes if requested
        let nodes = if limit.unwrap_or(0) > 0 {{
            self.{table_name}(ctx, where_, order_by, limit, offset, distinct_on).await?
        }} else {{
            Vec::new()
        }};
        
        Ok({model_name}Aggregate {{
            aggregate: Some({model_name}AggregateFields {{
                count: Some(count_row.0 as i32),
            }}),
            nodes,
        }})
    }}

"#,
            model_name = model_name,
            model_lower = model_lower,
            table_name = table_name,
        ))
    }
    
    /// Generate Mutation resolvers following Hasura v2 conventions
    fn generate_mutation_resolvers(&self, models: &[Model]) -> Result<String> {
        let mut mutation_impl = String::new();
        
        mutation_impl.push_str("#[Object]\nimpl Mutation {\n");
        
        for model in models {
            // Skip Block types and enum types
            if model.name.ends_with("Block") || model.fields.contains_key("_enum_type") {
                continue;
            }
            
            let model_name = &model.name;
            let model_lower = model_name.to_lowercase();
            
            // Generate insert_one mutation
            mutation_impl.push_str(&self.generate_insert_one_mutation(model)?);
            
            // Generate insert mutation (for multiple records)
            mutation_impl.push_str(&self.generate_insert_mutation(model)?);
            
            // Generate update_by_pk mutation
            mutation_impl.push_str(&self.generate_update_by_pk_mutation(model)?);
            
            // Generate update mutation (for multiple records)
            mutation_impl.push_str(&self.generate_update_mutation(model)?);
            
            // Generate delete_by_pk mutation
            mutation_impl.push_str(&self.generate_delete_by_pk_mutation(model)?);
            
            // Generate delete mutation (for multiple records)
            mutation_impl.push_str(&self.generate_delete_mutation(model)?);
        }
        
        mutation_impl.push_str("}\n\n");
        Ok(mutation_impl)
    }
    
    /// Generate insert_one mutation following Hasura v2 conventions
    fn generate_insert_one_mutation(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let model_lower = model_name.to_lowercase();
        
        Ok(format!(
            r#"    /// Insert a single {model_lower}
    async fn insert_{model_lower}_one(
        &self,
        ctx: &Context<'_>,
        object: {model_name}InsertInput,
        on_conflict: Option<{model_name}OnConflict>,
    ) -> FieldResult<Option<{model_name}>> {{
        let pool = ctx.data::<PgPool>()?;
        
        // Generate UUID for new record
        let id = uuid::Uuid::new_v4().to_string();
        let now = chrono::Utc::now();
        
        // Build insert query
        let mut fields = vec!["id", "created_at", "updated_at"];
        let mut placeholders = vec!["$1", "$2", "$3"];
        let mut param_count = 4;
        
        {field_processing}
        
        let fields_str = fields.join(", ");
        let placeholders_str = placeholders.join(", ");
        
        let query = format!(
            "INSERT INTO {model_lower} ({{}}) VALUES ({{}}) RETURNING *",
            fields_str, placeholders_str
        );
        
        // Execute insert
        let mut query_builder = sqlx::query_as::<_, {model_name}Row>(&query)
            .bind(id)
            .bind(now)
            .bind(now);
        
        {bind_parameters}
        
        let row = query_builder.fetch_one(pool).await?;
        
        Ok(Some(row.into()))
    }}

"#,
            model_name = model_name,
            model_lower = model_lower,
            field_processing = self.generate_insert_field_processing(model)?,
            bind_parameters = self.generate_insert_bind_parameters(model)?,
        ))
    }
    
    /// Build boolean expression SQL following Hasura v2 conventions
    fn build_bool_exp_sql(&self, _bool_exp: &str, _param_count: &mut i32) -> Result<(String, Vec<String>)> {
        // This would be implemented to handle complex boolean expressions
        // For now, returning placeholder
        Ok(("1=1".to_string(), Vec::new()))
    }
    
    /// Build ORDER BY SQL following Hasura v2 conventions
    fn build_order_by_sql(&self, _order_by: &str) -> Result<String> {
        // This would be implemented to handle order by clauses
        // For now, returning placeholder
        Ok("id ASC".to_string())
    }
    
    /// Generate field processing for insert operations
    fn generate_insert_field_processing(&self, model: &Model) -> Result<String> {
        let mut processing = String::new();
        
        for (field_name, field) in &model.fields {
            if field_name == "id" || field_name == "createdAt" || field_name == "updatedAt" {
                continue;
            }
            
            let db_field_name = self.camel_to_snake_case(field_name);
            processing.push_str(&format!(
                r#"        
        if object.{}.is_some() {{
            fields.push("{}");
            placeholders.push(&format!("${{}}", param_count));
            param_count += 1;
        }}"#,
                field_name, db_field_name
            ));
        }
        
        Ok(processing)
    }
    
    /// Generate parameter binding for insert operations
    fn generate_insert_bind_parameters(&self, model: &Model) -> Result<String> {
        let mut bindings = String::new();
        
        for (field_name, field) in &model.fields {
            if field_name == "id" || field_name == "createdAt" || field_name == "updatedAt" {
                continue;
            }
            
            bindings.push_str(&format!(
                r#"        
        if let Some(value) = object.{} {{
            query_builder = query_builder.bind(value);
        }}"#,
                field_name
            ));
        }
        
        Ok(bindings)
    }
    
    // Placeholder implementations for other mutation types
    fn generate_insert_mutation(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let model_lower = model_name.to_lowercase();
        
        Ok(format!(
            r#"    /// Insert multiple {model_lower}s
    async fn insert_{model_lower}(
        &self,
        ctx: &Context<'_>,
        objects: Vec<{model_name}InsertInput>,
        on_conflict: Option<{model_name}OnConflict>,
    ) -> FieldResult<{model_name}MutationResponse> {{
        // TODO: Implement batch insert
        Ok({model_name}MutationResponse {{
            affected_rows: 0,
            returning: Vec::new(),
        }})
    }}

"#,
            model_name = model_name,
            model_lower = model_lower,
        ))
    }
    
    fn generate_update_by_pk_mutation(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let model_lower = model_name.to_lowercase();
        
        Ok(format!(
            r#"    /// Update {model_lower} by primary key
    async fn update_{model_lower}_by_pk(
        &self,
        ctx: &Context<'_>,
        pk_columns: {model_name}PkColumnsInput,
        _set: Option<{model_name}SetInput>,
        _inc: Option<{model_name}IncInput>,
        _append: Option<{model_name}AppendInput>,
        _prepend: Option<{model_name}PrependInput>,
        _delete_key: Option<{model_name}DeleteKeyInput>,
        _delete_elem: Option<{model_name}DeleteElemInput>,
        _delete_at_path: Option<{model_name}DeleteAtPathInput>,
    ) -> FieldResult<Option<{model_name}>> {{
        // TODO: Implement update by pk
        Ok(None)
    }}

"#,
            model_name = model_name,
            model_lower = model_lower,
        ))
    }
    
    fn generate_update_mutation(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let model_lower = model_name.to_lowercase();
        
        Ok(format!(
            r#"    /// Update multiple {model_lower}s
    async fn update_{model_lower}(
        &self,
        ctx: &Context<'_>,
        where_: {model_name}BoolExp,
        _set: Option<{model_name}SetInput>,
        _inc: Option<{model_name}IncInput>,
        _append: Option<{model_name}AppendInput>,
        _prepend: Option<{model_name}PrependInput>,
        _delete_key: Option<{model_name}DeleteKeyInput>,
        _delete_elem: Option<{model_name}DeleteElemInput>,
        _delete_at_path: Option<{model_name}DeleteAtPathInput>,
    ) -> FieldResult<{model_name}MutationResponse> {{
        // TODO: Implement batch update
        Ok({model_name}MutationResponse {{
            affected_rows: 0,
            returning: Vec::new(),
        }})
    }}

"#,
            model_name = model_name,
            model_lower = model_lower,
        ))
    }
    
    fn generate_delete_by_pk_mutation(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let model_lower = model_name.to_lowercase();
        
        Ok(format!(
            r#"    /// Delete {model_lower} by primary key
    async fn delete_{model_lower}_by_pk(
        &self,
        ctx: &Context<'_>,
        id: ID,
    ) -> FieldResult<Option<{model_name}>> {{
        let pool = ctx.data::<PgPool>()?;
        
        let entity = sqlx::query_as::<_, {model_name}Row>(
            "DELETE FROM {model_lower} WHERE id = $1 RETURNING *"
        )
        .bind(id.to_string())
        .fetch_optional(pool)
        .await?;

        Ok(entity.map(|e| e.into()))
    }}

"#,
            model_name = model_name,
            model_lower = model_lower,
        ))
    }
    
    fn generate_delete_mutation(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let model_lower = model_name.to_lowercase();
        
        Ok(format!(
            r#"    /// Delete multiple {model_lower}s
    async fn delete_{model_lower}(
        &self,
        ctx: &Context<'_>,
        where_: {model_name}BoolExp,
    ) -> FieldResult<{model_name}MutationResponse> {{
        // TODO: Implement batch delete
        Ok({model_name}MutationResponse {{
            affected_rows: 0,
            returning: Vec::new(),
        }})
    }}

"#,
            model_name = model_name,
            model_lower = model_lower,
        ))
    }
    
    /// Generate resolver registration
    fn generate_resolver_registration(&self, _models: &[Model]) -> Result<String> {
        let registration = format!(r#"/// Build the complete GraphQL schema with Hasura v2 style resolvers
pub fn build_schema() -> async_graphql::Schema<Query, Mutation, EmptySubscription> {{
    async_graphql::Schema::build(Query, Mutation, EmptySubscription)
        .finish()
}}
"#);
        
        Ok(registration)
    }
}
