use anyhow::Result;
use crate::types::*;

/// Hasura v2 Style Type Generator
/// Generates GraphQL types following Hasura v2 conventions
pub struct HasuraV2TypeGenerator;

impl HasuraV2TypeGenerator {
    pub fn new() -> Self {
        Self
    }
    
    /// Generate header with imports and basic setup
    fn generate_header(&self) -> String {
        format!(r#"// Auto-generated Hasura v2 Style GraphQL types
// DO NOT EDIT - This file is automatically generated

use async_graphql::{{SimpleObject, InputObject, Enum, Union, ID, Object}};
use chrono::{{DateTime, Utc}};
use serde::{{Deserialize, Serialize}};
use uuid::Uuid;

"#)
    }
    
    /// Generate enum type with all required traits
    fn generate_enum_type(&self, model: &Model) -> Result<String> {
        let enum_name = &model.name;
        
        // Get enum values from _enum_type field
        let enum_values = match enum_name.as_str() {
            "DealStage" => vec!["LEAD", "QUALIFIED", "PROPOSAL", "NEGOTIATION", "WON", "LOST"],
            "CompanySize" => vec!["STARTUP", "SMALL", "MEDIUM", "LARGE", "ENTERPRISE"],
            _ => vec!["VALUE1", "VALUE2", "VALUE3"],
        };
        
        let mut result = String::new();
        
        // Enum declaration - remove conflicting derives
        result.push_str(&format!("/// {} enumeration\n", enum_name));
        result.push_str("#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, async_graphql::Enum, Copy, Default)]\n");
        result.push_str(&format!("pub enum {} {{\n", enum_name));
        
        let mut first = true;
        for value in &enum_values {
            if first {
                result.push_str(&format!("    #[default]\n    {},\n", value));
                first = false;
            } else {
                result.push_str(&format!("    {},\n", value));
            }
        }
        result.push_str("}\n\n");
        
        // Display implementation
        result.push_str(&format!("impl std::fmt::Display for {} {{\n", enum_name));
        result.push_str("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
        result.push_str("        let s = match self {\n");
        
        for value in &enum_values {
            result.push_str(&format!("            Self::{} => \"{}\",\n", value, value));
        }
        
        result.push_str("        };\n");
        result.push_str("        write!(f, \"{}\", s)\n");
        result.push_str("    }\n");
        result.push_str("}\n\n");
        
        // FromStr implementation
        result.push_str(&format!("impl std::str::FromStr for {} {{\n", enum_name));
        result.push_str("    type Err = String;\n");
        result.push_str("    \n");
        result.push_str("    fn from_str(s: &str) -> Result<Self, Self::Err> {\n");
        result.push_str("        match s {\n");
        
        for value in &enum_values {
            result.push_str(&format!("            \"{}\" => Ok(Self::{}),\n", value, value));
        }
        
        result.push_str(&format!("            _ => Err(format!(\"Invalid {}: {{}}\", s)),\n", enum_name));
        result.push_str("        }\n");
        result.push_str("    }\n");
        result.push_str("}\n\n");
        
        // sqlx Type trait
        result.push_str(&format!("impl sqlx::Type<sqlx::Postgres> for {} {{\n", enum_name));
        result.push_str("    fn type_info() -> sqlx::postgres::PgTypeInfo {\n");
        result.push_str("        sqlx::postgres::PgTypeInfo::with_name(\"text\")\n");
        result.push_str("    }\n");
        result.push_str("}\n\n");
        
        // sqlx Decode
        result.push_str(&format!("impl<'r> sqlx::Decode<'r, sqlx::Postgres> for {} {{\n", enum_name));
        result.push_str("    fn decode(value: sqlx::postgres::PgValueRef<'r>) -> Result<Self, sqlx::error::BoxDynError> {\n");
        result.push_str("        let s = <&str as sqlx::Decode<sqlx::Postgres>>::decode(value)?;\n");
        result.push_str("        s.parse().map_err(|e| Box::new(std::io::Error::new(std::io::ErrorKind::InvalidData, e)) as Box<dyn std::error::Error + Send + Sync>)\n");
        result.push_str("    }\n");
        result.push_str("}\n\n");
        
        // sqlx Encode
        result.push_str(&format!("impl<'q> sqlx::Encode<'q, sqlx::Postgres> for {} {{\n", enum_name));
        result.push_str("    fn encode_by_ref(&self, buf: &mut sqlx::postgres::PgArgumentBuffer) -> sqlx::encode::IsNull {\n");
        result.push_str("        <String as sqlx::Encode<'q, sqlx::Postgres>>::encode_by_ref(&self.to_string(), buf)\n");
        result.push_str("    }\n");
        result.push_str("}\n\n");
        
        Ok(result)
    }
    
    /// Generate all Hasura v2 style types for models
    pub fn generate_types(&self, models: &[Model]) -> Result<String> {
        let mut types = String::new();
        
        // Add header
        types.push_str(&self.generate_header());
        
        // Generate enums first
        for model in models {
            if model.fields.contains_key("_enum_type") {
                types.push_str(&self.generate_enum_type(model)?);
            }
        }
        
        // Generate basic model types
        for model in models {
            if model.name.ends_with("Block") || model.fields.contains_key("_enum_type") {
                continue;
            }
            
            types.push_str(&self.generate_model_type(model)?);
            types.push_str(&self.generate_row_type(model)?);
            types.push_str(&self.generate_bool_exp_type(model)?);
            types.push_str(&self.generate_order_by_type(model)?);
            types.push_str(&self.generate_select_column_type(model)?);
            types.push_str(&self.generate_aggregate_type(model)?);
            types.push_str(&self.generate_aggregate_fields_type(model)?);
            types.push_str(&self.generate_insert_input_type(model)?);
            types.push_str(&self.generate_set_input_type(model)?);
            types.push_str(&self.generate_inc_input_type(model)?);
            types.push_str(&self.generate_append_input_type(model)?);
            types.push_str(&self.generate_prepend_input_type(model)?);
            types.push_str(&self.generate_delete_key_input_type(model)?);
            types.push_str(&self.generate_delete_elem_input_type(model)?);
            types.push_str(&self.generate_delete_at_path_input_type(model)?);
            types.push_str(&self.generate_pk_columns_input_type(model)?);
            types.push_str(&self.generate_on_conflict_type(model)?);
            types.push_str(&self.generate_mutation_response_type(model)?);
        }
        
        // Generate comparison operators
        types.push_str(&self.generate_comparison_operators());
        
        Ok(types)
    }
    
    /// Convert camelCase to snake_case for database field names
    fn camel_to_snake_case(&self, input: &str) -> String {
        let mut result = String::new();
        let mut chars = input.chars().peekable();
        
        while let Some(ch) = chars.next() {
            if ch.is_uppercase() && !result.is_empty() {
                result.push('_');
            }
            result.push(ch.to_lowercase().next().unwrap());
        }
        
        result
    }
    
    /// Generate basic model type
    fn generate_model_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let mut fields = Vec::new();
        
        for (field_name, field) in &model.fields {
            let field_type = self.convert_field_type(&field.field_type, field.optional);
            
            fields.push(format!("    pub {}: {}", field_name, field_type));
        }
        
        let fields_str = fields.join(",\n");
        
        Ok(format!(
            r#"/// {model_name} entity
#[derive(SimpleObject, Debug, Clone)]
pub struct {model_name} {{
{fields_str},
}}

"#,
            model_name = model_name,
            fields_str = fields_str,
        ))
    }
    
    /// Generate database row type for sqlx
    fn generate_row_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let mut fields = Vec::new();
        
        for (field_name, field) in &model.fields {
            let db_field_name = self.camel_to_snake_case(field_name);
            let field_type = self.convert_field_type_for_db(&field.field_type, field.optional);
            
            fields.push(format!("    pub {}: {}", db_field_name, field_type));
        }
        
        let fields_str = fields.join(",\n");
        
        // Generate From implementation
        let mut from_fields = Vec::new();
        for (field_name, field) in &model.fields {
            let db_field_name = self.camel_to_snake_case(field_name);
            
            // Handle BigDecimal to f64 conversion for numeric fields
            let conversion = match &field.field_type {
                FieldType::Number if field.optional => {
                    format!("            {}: row.{}.map(|v| v.to_string().parse::<f64>().unwrap_or(0.0))", field_name, db_field_name)
                },
                FieldType::Number => {
                    format!("            {}: row.{}.to_string().parse::<f64>().unwrap_or(0.0)", field_name, db_field_name)
                },
                FieldType::Array(_) if field.optional => {
                    format!("            {}: row.{}.as_ref().and_then(|v| serde_json::from_value(v.clone()).ok()).unwrap_or_default()", field_name, db_field_name)
                },
                FieldType::Array(_) => {
                    format!("            {}: serde_json::from_value(row.{}).unwrap_or_default()", field_name, db_field_name)
                },
                FieldType::Custom(custom_type) if field.optional => {
                    format!("            {}: row.{}.map(|s| s.parse().unwrap_or_default())", field_name, db_field_name)
                },
                FieldType::Custom(custom_type) => {
                    format!("            {}: row.{}.parse().unwrap_or_default()", field_name, db_field_name)
                },
                _ => {
                    format!("            {}: row.{}", field_name, db_field_name)
                }
            };
            
            from_fields.push(conversion);
        }
        let from_fields_str = from_fields.join(",\n");
        
        Ok(format!(
            r#"/// Database row type for {model_name}
#[derive(sqlx::FromRow, Debug, Clone)]
pub struct {model_name}Row {{
{fields_str},
}}

impl From<{model_name}Row> for {model_name} {{
    fn from(row: {model_name}Row) -> Self {{
        Self {{
{from_fields_str},
        }}
    }}
}}

"#,
            model_name = model_name,
            fields_str = fields_str,
            from_fields_str = from_fields_str,
        ))
    }
    
    /// Generate boolean expression type for filtering (Hasura v2 style)
    fn generate_bool_exp_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let mut fields = Vec::new();
        
        // Add logical operators
        fields.push(format!("    pub _and: Option<Vec<{model_name}BoolExp>>"));
        fields.push(format!("    pub _or: Option<Vec<{model_name}BoolExp>>"));
        fields.push(format!("    pub _not: Option<Box<{model_name}BoolExp>>"));
        
        // Add field-specific filters
        for (field_name, field) in &model.fields {
            let comparison_type = self.get_comparison_type(&field.field_type);
            fields.push(format!("    pub {}: Option<{}>", field_name, comparison_type));
        }
        
        let fields_str = fields.join(",\n");
        
        Ok(format!(
            r#"/// Boolean expression for filtering {model_name}
#[derive(InputObject, Debug, Clone)]
pub struct {model_name}BoolExp {{
{fields_str},
}}

"#,
            model_name = model_name,
            fields_str = fields_str,
        ))
    }
    
    /// Generate order by type (Hasura v2 style)
    fn generate_order_by_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let mut fields = Vec::new();
        
        for (field_name, _) in &model.fields {
            fields.push(format!("    pub {}: Option<OrderBy>", field_name));
        }
        
        let fields_str = fields.join(",\n");
        
        Ok(format!(
            r#"/// Order by input for {model_name}
#[derive(InputObject, Debug, Clone)]
pub struct {model_name}OrderBy {{
{fields_str},
}}

"#,
            model_name = model_name,
            fields_str = fields_str,
        ))
    }
    
    /// Generate select column enum
    fn generate_select_column_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let mut variants = Vec::new();
        
        for (field_name, _) in &model.fields {
            variants.push(field_name.clone());
        }
        
        let variants_str = variants.join(",\n    ");
        
        Ok(format!(
            r#"/// Select columns for {model_name}
#[derive(Enum, Debug, Clone, Copy, PartialEq, Eq)]
pub enum {model_name}SelectColumn {{
    {variants_str},
}}

"#,
            model_name = model_name,
            variants_str = variants_str,
        ))
    }
    
    /// Generate insert input type
    fn generate_insert_input_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let mut fields = Vec::new();
        
        for (field_name, field) in &model.fields {
            // Skip auto-generated fields
            if field_name == "id" || field_name == "createdAt" || field_name == "updatedAt" {
                continue;
            }
            
            let field_type = self.convert_field_type(&field.field_type, false); // Get base type without Option
            fields.push(format!("    pub {}: Option<{}>", field_name, field_type));
        }
        
        let fields_str = fields.join(",\n");
        
        Ok(format!(
            r#"/// Insert input for {model_name}
#[derive(InputObject, Debug, Clone)]
pub struct {model_name}InsertInput {{
{fields_str},
}}

"#,
            model_name = model_name,
            fields_str = fields_str,
        ))
    }
    
    /// Generate set input type for updates
    fn generate_set_input_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let mut fields = Vec::new();
        
        for (field_name, field) in &model.fields {
            // Skip id and auto-generated fields for updates
            if field_name == "id" || field_name == "createdAt" {
                continue;
            }
            
            let field_type = self.convert_field_type(&field.field_type, false); // Get base type without Option
            fields.push(format!("    pub {}: Option<{}>", field_name, field_type));
        }
        
        let fields_str = fields.join(",\n");
        
        Ok(format!(
            r#"/// Set input for updating {model_name}
#[derive(InputObject, Debug, Clone)]
pub struct {model_name}SetInput {{
{fields_str},
}}

"#,
            model_name = model_name,
            fields_str = fields_str,
        ))
    }
    
    /// Generate primary key columns input
    fn generate_pk_columns_input_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        Ok(format!(
            r#"/// Primary key columns input for {model_name}
#[derive(InputObject, Debug, Clone)]
pub struct {model_name}PkColumnsInput {{
    pub id: ID,
}}

"#,
            model_name = model_name,
        ))
    }
    
    /// Generate on conflict type
    fn generate_on_conflict_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        Ok(format!(
            r#"/// On conflict input for {model_name}
#[derive(InputObject, Debug, Clone)]
pub struct {model_name}OnConflict {{
    pub constraint: {model_name}Constraint,
    pub update_columns: Vec<{model_name}UpdateColumn>,
    pub where_: Option<{model_name}BoolExp>,
}}

/// Constraint enum for {model_name}
#[derive(Enum, Debug, Clone, Copy, PartialEq, Eq)]
pub enum {model_name}Constraint {{
    {model_name}Pkey,
}}

/// Update column enum for {model_name}
#[derive(Enum, Debug, Clone, Copy, PartialEq, Eq)]
pub enum {model_name}UpdateColumn {{
    // Add update columns based on fields
    Id,
    CreatedAt,
    UpdatedAt,
}}

"#,
            model_name = model_name,
        ))
    }
    
    /// Generate mutation response type
    fn generate_mutation_response_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        Ok(format!(
            r#"/// Mutation response for {model_name}
#[derive(SimpleObject, Debug, Clone)]
pub struct {model_name}MutationResponse {{
    pub affected_rows: i32,
    pub returning: Vec<{model_name}>,
}}

"#,
            model_name = model_name,
        ))
    }
    
    /// Generate aggregate types
    fn generate_aggregate_types(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        Ok(format!(
            r#"/// Aggregate type for {model_name}
#[derive(SimpleObject, Debug, Clone)]
pub struct {model_name}Aggregate {{
    pub aggregate: Option<{model_name}AggregateFields>,
    pub nodes: Vec<{model_name}>,
}}

/// Aggregate fields for {model_name}
#[derive(SimpleObject, Debug, Clone)]
pub struct {model_name}AggregateFields {{
    pub count: Option<i32>,
    // Add more aggregate fields like sum, avg, max, min as needed
}}

"#,
            model_name = model_name,
        ))
    }
    
    /// Generate comparison operators
    fn generate_comparison_operators(&self) -> String {
        format!(r#"/// Order by enum
#[derive(Enum, Debug, Clone, Copy, PartialEq, Eq)]
pub enum OrderBy {{
    Asc,
    AscNullsFirst,
    AscNullsLast,
    Desc,
    DescNullsFirst,
    DescNullsLast,
}}

/// String comparison expression
#[derive(InputObject, Debug, Clone)]
pub struct StringComparisonExp {{
    pub _eq: Option<String>,
    pub _neq: Option<String>,
    pub _gt: Option<String>,
    pub _gte: Option<String>,
    pub _lt: Option<String>,
    pub _lte: Option<String>,
    pub _like: Option<String>,
    pub _ilike: Option<String>,
    pub _similar: Option<String>,
    pub _regex: Option<String>,
    pub _iregex: Option<String>,
    pub _in: Option<Vec<String>>,
    pub _nin: Option<Vec<String>>,
    pub _is_null: Option<bool>,
}}

/// Integer comparison expression
#[derive(InputObject, Debug, Clone)]
pub struct IntComparisonExp {{
    pub _eq: Option<i32>,
    pub _neq: Option<i32>,
    pub _gt: Option<i32>,
    pub _gte: Option<i32>,
    pub _lt: Option<i32>,
    pub _lte: Option<i32>,
    pub _in: Option<Vec<i32>>,
    pub _nin: Option<Vec<i32>>,
    pub _is_null: Option<bool>,
}}

/// Float comparison expression
#[derive(InputObject, Debug, Clone)]
pub struct FloatComparisonExp {{
    pub _eq: Option<f64>,
    pub _neq: Option<f64>,
    pub _gt: Option<f64>,
    pub _gte: Option<f64>,
    pub _lt: Option<f64>,
    pub _lte: Option<f64>,
    pub _in: Option<Vec<f64>>,
    pub _nin: Option<Vec<f64>>,
    pub _is_null: Option<bool>,
}}

/// Boolean comparison expression
#[derive(InputObject, Debug, Clone)]
pub struct BooleanComparisonExp {{
    pub _eq: Option<bool>,
    pub _neq: Option<bool>,
    pub _is_null: Option<bool>,
}}

/// DateTime comparison expression
#[derive(InputObject, Debug, Clone)]
pub struct DateTimeComparisonExp {{
    pub _eq: Option<DateTime<Utc>>,
    pub _neq: Option<DateTime<Utc>>,
    pub _gt: Option<DateTime<Utc>>,
    pub _gte: Option<DateTime<Utc>>,
    pub _lt: Option<DateTime<Utc>>,
    pub _lte: Option<DateTime<Utc>>,
    pub _in: Option<Vec<DateTime<Utc>>>,
    pub _nin: Option<Vec<DateTime<Utc>>>,
    pub _is_null: Option<bool>,
}}

/// ID comparison expression
#[derive(InputObject, Debug, Clone)]
pub struct IdComparisonExp {{
    pub _eq: Option<ID>,
    pub _neq: Option<ID>,
    pub _in: Option<Vec<ID>>,
    pub _nin: Option<Vec<ID>>,
    pub _is_null: Option<bool>,
}}

"#)
    }
    
    /// Convert field type to Rust type
    fn convert_field_type(&self, field_type: &FieldType, optional: bool) -> String {
        let base_type = match field_type {
            FieldType::String => "String".to_string(),
            FieldType::Number => "f64".to_string(),
            FieldType::Boolean => "bool".to_string(),
            FieldType::Date | FieldType::DateTime => "DateTime<Utc>".to_string(),
            FieldType::EntityId => "ID".to_string(),
            FieldType::Json => "serde_json::Value".to_string(),
            FieldType::Blocks => "serde_json::Value".to_string(),
            FieldType::Array(inner) => format!("Vec<{}>", self.convert_field_type(inner, false)),
            FieldType::Custom(name) => name.clone(),
            FieldType::Reference(name) => name.clone(),
        };
        
        if optional {
            format!("Option<{}>", base_type)
        } else {
            base_type
        }
    }
    
    /// Convert field type for database row
    fn convert_field_type_for_db(&self, field_type: &FieldType, optional: bool) -> String {
        let base_type = match field_type {
            FieldType::String => "String".to_string(),
            FieldType::Number => "sqlx::types::BigDecimal".to_string(),
            FieldType::Boolean => "bool".to_string(),
            FieldType::Date | FieldType::DateTime => "DateTime<Utc>".to_string(),
            FieldType::EntityId => "String".to_string(),
            FieldType::Json => "serde_json::Value".to_string(),
            FieldType::Blocks => "serde_json::Value".to_string(),
            // Store arrays as JSONB in database for better compatibility
            FieldType::Array(_) => "serde_json::Value".to_string(),
            FieldType::Custom(_) => "String".to_string(), // Store custom types as strings in DB
            FieldType::Reference(_) => "String".to_string(), // Store references as strings in DB
        };
        
        if optional {
            format!("Option<{}>", base_type)
        } else {
            base_type
        }
    }
    
    /// Get comparison type for field
    fn get_comparison_type(&self, field_type: &FieldType) -> String {
        match field_type {
            FieldType::String => "StringComparisonExp".to_string(),
            FieldType::Number => "FloatComparisonExp".to_string(),
            FieldType::Boolean => "BooleanComparisonExp".to_string(),
            FieldType::Date | FieldType::DateTime => "DateTimeComparisonExp".to_string(),
            FieldType::EntityId => "IdComparisonExp".to_string(),
            FieldType::Json => "StringComparisonExp".to_string(), // Treat JSON as string for comparison
            FieldType::Blocks => "StringComparisonExp".to_string(),
            FieldType::Array(_) => "StringComparisonExp".to_string(), // Arrays compared as strings
            FieldType::Custom(_) => "StringComparisonExp".to_string(),
            FieldType::Reference(_) => "StringComparisonExp".to_string(),
        }
    }
    
    /// Generate inc input type for numeric operations
    fn generate_inc_input_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let mut fields = Vec::new();
        
        for (field_name, field) in &model.fields {
            if matches!(field.field_type, FieldType::Number) {
                fields.push(format!("    pub {}: Option<i32>", field_name));
            }
        }
        
        if fields.is_empty() {
            fields.push("    pub _placeholder: Option<String>".to_string());
        }
        
        let fields_str = fields.join(",\n");
        
        Ok(format!(
            r#"/// Inc input for {model_name}
#[derive(InputObject, Debug, Clone)]
pub struct {model_name}IncInput {{
{fields_str},
}}

"#,
            model_name = model_name,
            fields_str = fields_str,
        ))
    }
    
    /// Generate append input type
    fn generate_append_input_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        Ok(format!(
            r#"/// Append input for {model_name}
#[derive(InputObject, Debug, Clone)]
pub struct {model_name}AppendInput {{
    pub _placeholder: Option<String>,
}}

"#,
            model_name = model_name,
        ))
    }
    
    /// Generate prepend input type
    fn generate_prepend_input_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        Ok(format!(
            r#"/// Prepend input for {model_name}
#[derive(InputObject, Debug, Clone)]
pub struct {model_name}PrependInput {{
    pub _placeholder: Option<String>,
}}

"#,
            model_name = model_name,
        ))
    }
    
    /// Generate delete key input type
    fn generate_delete_key_input_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        Ok(format!(
            r#"/// Delete key input for {model_name}
#[derive(InputObject, Debug, Clone)]
pub struct {model_name}DeleteKeyInput {{
    pub _placeholder: Option<String>,
}}

"#,
            model_name = model_name,
        ))
    }
    
    /// Generate delete elem input type
    fn generate_delete_elem_input_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        Ok(format!(
            r#"/// Delete elem input for {model_name}
#[derive(InputObject, Debug, Clone)]
pub struct {model_name}DeleteElemInput {{
    pub _placeholder: Option<String>,
}}

"#,
            model_name = model_name,
        ))
    }
    
    /// Generate delete at path input type
    fn generate_delete_at_path_input_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        Ok(format!(
            r#"/// Delete at path input for {model_name}
#[derive(InputObject, Debug, Clone)]
pub struct {model_name}DeleteAtPathInput {{
    pub _placeholder: Option<String>,
}}

"#,
            model_name = model_name,
        ))
    }
    
    /// Generate aggregate type for Hasura v2 style queries
    fn generate_aggregate_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        Ok(format!(
            r#"/// {model_name} aggregate type
#[derive(SimpleObject, Clone, Debug)]
pub struct {model_name}Aggregate {{
    pub aggregate: Option<{model_name}AggregateFields>,
    pub nodes: Vec<{model_name}>,
}}

"#,
            model_name = model_name,
        ))
    }
    
    /// Generate aggregate fields type for Hasura v2 style queries
    fn generate_aggregate_fields_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        Ok(format!(
            r#"/// {model_name} aggregate fields type
#[derive(SimpleObject, Clone, Debug)]
pub struct {model_name}AggregateFields {{
    pub count: Option<i32>,
}}

"#,
            model_name = model_name,
        ))
    }
    
}
