use anyhow::Result;
use crate::types::*;
use crate::operation_definitions::OperationDefinitions;

/// Hasura v2 Style Type Generator
/// Generates GraphQL types following Hasura v2 conventions
pub struct HasuraV2TypeGenerator;

impl HasuraV2TypeGenerator {
    pub fn new() -> Self {
        Self
    }
    
    /// Generate header with imports and basic setup
    fn generate_header(&self) -> String {
        format!(r#"// Auto-generated Hasura v2 Style GraphQL types
// DO NOT EDIT - This file is automatically generated

use async_graphql::{{SimpleObject, InputObject, Enum, Union, ID, Object}};
use chrono::{{DateTime, Utc}};
use serde::{{Deserialize, Serialize}};
use uuid::Uuid;

"#)
    }
    
    /// Generate enum type with all required traits
    fn generate_enum_type(&self, model: &Model) -> Result<String> {
        let enum_name = &model.name;
        
        // Get enum values from _enum_type field
        let enum_values = match enum_name.as_str() {
            // Platform core should not have knowledge of specific business domain enum values
            // All domain-specific enums should be defined in their respective services
            _ => vec!["VALUE1", "VALUE2", "VALUE3"],
        };
        
        let mut result = String::new();
        
        // Enum declaration - remove conflicting derives
        result.push_str(&format!("/// {} enumeration\n", enum_name));
        result.push_str("#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, async_graphql::Enum, Copy, Default)]\n");
        result.push_str(&format!("pub enum {} {{\n", enum_name));
        
        let mut first = true;
        for value in &enum_values {
            if first {
                result.push_str(&format!("    #[default]\n    {},\n", value));
                first = false;
            } else {
                result.push_str(&format!("    {},\n", value));
            }
        }
        result.push_str("}\n\n");
        
        // Display implementation
        result.push_str(&format!("impl std::fmt::Display for {} {{\n", enum_name));
        result.push_str("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
        result.push_str("        let s = match self {\n");
        
        for value in &enum_values {
            result.push_str(&format!("            Self::{} => \"{}\",\n", value, value));
        }
        
        result.push_str("        };\n");
        result.push_str("        write!(f, \"{}\", s)\n");
        result.push_str("    }\n");
        result.push_str("}\n\n");
        
        // FromStr implementation
        result.push_str(&format!("impl std::str::FromStr for {} {{\n", enum_name));
        result.push_str("    type Err = String;\n");
        result.push_str("    \n");
        result.push_str("    fn from_str(s: &str) -> Result<Self, Self::Err> {\n");
        result.push_str("        match s {\n");
        
        for value in &enum_values {
            result.push_str(&format!("            \"{}\" => Ok(Self::{}),\n", value, value));
        }
        
        result.push_str(&format!("            _ => Err(format!(\"Invalid {}: {{}}\", s)),\n", enum_name));
        result.push_str("        }\n");
        result.push_str("    }\n");
        result.push_str("}\n\n");
        
        // sqlx Type trait
        result.push_str(&format!("impl sqlx::Type<sqlx::Postgres> for {} {{\n", enum_name));
        result.push_str("    fn type_info() -> sqlx::postgres::PgTypeInfo {\n");
        result.push_str("        sqlx::postgres::PgTypeInfo::with_name(\"text\")\n");
        result.push_str("    }\n");
        result.push_str("}\n\n");
        
        // sqlx Decode
        result.push_str(&format!("impl<'r> sqlx::Decode<'r, sqlx::Postgres> for {} {{\n", enum_name));
        result.push_str("    fn decode(value: sqlx::postgres::PgValueRef<'r>) -> Result<Self, sqlx::error::BoxDynError> {\n");
        result.push_str("        let s = <&str as sqlx::Decode<sqlx::Postgres>>::decode(value)?;\n");
        result.push_str("        s.parse().map_err(|e| Box::new(std::io::Error::new(std::io::ErrorKind::InvalidData, e)) as Box<dyn std::error::Error + Send + Sync>)\n");
        result.push_str("    }\n");
        result.push_str("}\n\n");
        
        // sqlx Encode
        result.push_str(&format!("impl<'q> sqlx::Encode<'q, sqlx::Postgres> for {} {{\n", enum_name));
        result.push_str("    fn encode_by_ref(&self, buf: &mut sqlx::postgres::PgArgumentBuffer) -> sqlx::encode::IsNull {\n");
        result.push_str("        <String as sqlx::Encode<'q, sqlx::Postgres>>::encode_by_ref(&self.to_string(), buf)\n");
        result.push_str("    }\n");
        result.push_str("}\n\n");
        
        Ok(result)
    }
    
    /// Generate all Hasura v2 style types for models
    pub fn generate_types(&self, models: &[Model]) -> Result<String> {
        let mut types = String::new();
        
        // Add header
        types.push_str(&self.generate_header());
        
        // Generate ContentBlock type alias
        types.push_str(&self.generate_content_block_union()?);
        
        // Note: Platform models (AuditLogEntry, PlatformUser, UserSession) are already defined 
        // in atomo_server::platform_models and included via GraphQL schema
        
        // Generate enums first
        for model in models {
            if model.fields.contains_key("_enum_type") {
                types.push_str(&self.generate_enum_type(model)?);
            }
        }
        
        // Generate basic model types
        for model in models {
            // Skip enum types and Block types as they are handled separately
            if model.fields.contains_key("_enum_type") || model.name.ends_with("Block") {
                continue;
            }
            
            types.push_str(&self.generate_model_type(model)?);
            types.push_str(&self.generate_row_type(model)?);
            types.push_str(&self.generate_bool_exp_type(model)?);
            types.push_str(&self.generate_order_by_type(model)?);
            types.push_str(&self.generate_select_column_type(model)?);
            types.push_str(&self.generate_aggregate_type(model)?);
            types.push_str(&self.generate_aggregate_fields_type(model)?);
            types.push_str(&self.generate_insert_input_type(model)?);
            types.push_str(&self.generate_set_input_type(model)?);
            types.push_str(&self.generate_inc_input_type(model)?);
            types.push_str(&self.generate_append_input_type(model)?);
            types.push_str(&self.generate_prepend_input_type(model)?);
            types.push_str(&self.generate_delete_key_input_type(model)?);
            types.push_str(&self.generate_delete_elem_input_type(model)?);
            types.push_str(&self.generate_delete_at_path_input_type(model)?);
            types.push_str(&self.generate_pk_columns_input_type(model)?);
            types.push_str(&self.generate_on_conflict_type(model)?);
            types.push_str(&self.generate_mutation_response_type(model)?);
        }
        
        // Generate comparison operators
        types.push_str(&self.generate_comparison_operators());
        
        Ok(types)
    }
    
    /// Generate ContentBlock union type for GraphQL
    fn generate_content_block_union(&self) -> Result<String> {
        Ok(format!(
            r#"/// ContentBlock GraphQL Union Type
#[derive(async_graphql::Union, Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "blockType")]
pub enum ContentBlock {{
    #[serde(rename = "paragraph")]
    Paragraph(ParagraphBlock),
    #[serde(rename = "call_log")]
    CallLog(CallLogBlock), 
    #[serde(rename = "meeting_note")]
    MeetingNote(MeetingNoteBlock),
    #[serde(rename = "task")]
    Task(TaskBlock),
}}

/// Paragraph content block
#[derive(Debug, Clone, Serialize, Deserialize, async_graphql::SimpleObject)]
pub struct ParagraphBlock {{
    pub id: String,
    pub content: String,
    pub metadata: Option<serde_json::Value>,
    pub order: i32,
    pub is_visible: bool,
}}

/// Call log content block
#[derive(Debug, Clone, Serialize, Deserialize, async_graphql::SimpleObject)]
pub struct CallLogBlock {{
    pub id: String,
    pub caller: String,
    pub duration: i32,
    pub notes: Option<String>,
    pub outcome: Option<String>,
    pub recorded_at: DateTime<Utc>,
    pub metadata: Option<serde_json::Value>,
    pub order: i32,
    pub is_visible: bool,
}}

/// Meeting note content block
#[derive(Debug, Clone, Serialize, Deserialize, async_graphql::SimpleObject)]
pub struct MeetingNoteBlock {{
    pub id: String,
    pub title: String,
    pub agenda: Option<String>,
    pub notes: String,
    pub attendees: Vec<String>,
    #[graphql(name = "actionItems")]
    pub action_items: Vec<String>,
    #[graphql(name = "meetingDate")]
    pub meeting_time: DateTime<Utc>,
    pub metadata: Option<serde_json::Value>,
    pub order: i32,
    pub is_visible: bool,
}}

/// Task content block
#[derive(Debug, Clone, Serialize, Deserialize, async_graphql::SimpleObject)]
pub struct TaskBlock {{
    pub id: String,
    pub title: String,
    pub description: Option<String>,
    #[graphql(name = "completed")]
    pub is_completed: bool,
    pub due_date: Option<DateTime<Utc>>,
    pub assigned_to: Option<String>,
    pub metadata: Option<serde_json::Value>,
    pub order: i32,
    pub is_visible: bool,
}}

// Conversion from atomo_core::ContentBlock to GraphQL ContentBlock union
impl ContentBlock {{
    pub fn from_core_block(core_block: &atomo_core::ContentBlock) -> Result<Self, Box<dyn std::error::Error>> {{
        let content: serde_json::Value = serde_json::from_str(&core_block.content)?;
        
        // Use content metadata to determine the specific block type
        let block_subtype = content.get("blockType").and_then(|v| v.as_str()).unwrap_or("text");
        
        match block_subtype {{
            "paragraph" => {{
                Ok(ContentBlock::Paragraph(ParagraphBlock {{
                    id: core_block.id.clone(),
                    content: content.get("content").and_then(|v| v.as_str()).unwrap_or("").to_string(),
                    metadata: core_block.metadata.clone().map(|s| serde_json::from_str(&s).unwrap_or(serde_json::Value::Null)),
                    order: core_block.order,
                    is_visible: core_block.is_visible,
                }}))
            }},
            "call_log" => {{
                Ok(ContentBlock::CallLog(CallLogBlock {{
                    id: core_block.id.clone(),
                    caller: content.get("caller").and_then(|v| v.as_str()).unwrap_or("").to_string(),
                    duration: content.get("duration").and_then(|v| v.as_i64()).unwrap_or(0) as i32,
                    notes: content.get("notes").and_then(|v| v.as_str()).map(|s| s.to_string()),
                    outcome: content.get("outcome").and_then(|v| v.as_str()).map(|s| s.to_string()),
                    recorded_at: chrono::Utc::now(), // TODO: Parse from content
                    metadata: core_block.metadata.clone().map(|s| serde_json::from_str(&s).unwrap_or(serde_json::Value::Null)),
                    order: core_block.order,
                    is_visible: core_block.is_visible,
                }}))
            }},
            "meeting_note" => {{
                Ok(ContentBlock::MeetingNote(MeetingNoteBlock {{
                    id: core_block.id.clone(),
                    title: content.get("title").and_then(|v| v.as_str()).unwrap_or("").to_string(),
                    agenda: content.get("agenda").and_then(|v| v.as_str()).map(|s| s.to_string()),
                    notes: content.get("notes").and_then(|v| v.as_str()).unwrap_or("").to_string(),
                    attendees: content.get("attendees").and_then(|v| v.as_array())
                        .map(|arr| arr.iter().filter_map(|v| v.as_str().map(|s| s.to_string())).collect())
                        .unwrap_or_default(),
                    action_items: content.get("actionItems").and_then(|v| v.as_array())
                        .map(|arr| arr.iter().filter_map(|v| v.as_str().map(|s| s.to_string())).collect())
                        .unwrap_or_default(),
                    meeting_time: chrono::Utc::now(), // TODO: Parse from content
                    metadata: core_block.metadata.clone().map(|s| serde_json::from_str(&s).unwrap_or(serde_json::Value::Null)),
                    order: core_block.order,
                    is_visible: core_block.is_visible,
                }}))
            }},
            "task" => {{
                Ok(ContentBlock::Task(TaskBlock {{
                    id: core_block.id.clone(),
                    title: content.get("title").and_then(|v| v.as_str()).unwrap_or("").to_string(),
                    description: content.get("description").and_then(|v| v.as_str()).map(|s| s.to_string()),
                    is_completed: content.get("isCompleted").and_then(|v| v.as_bool()).unwrap_or(false),
                    due_date: None, // TODO: Parse from content
                    assigned_to: content.get("assignedTo").and_then(|v| v.as_str()).map(|s| s.to_string()),
                    metadata: core_block.metadata.clone().map(|s| serde_json::from_str(&s).unwrap_or(serde_json::Value::Null)),
                    order: core_block.order,
                    is_visible: core_block.is_visible,
                }}))
            }},
            _ => {{
                // Default to paragraph for unknown types
                Ok(ContentBlock::Paragraph(ParagraphBlock {{
                    id: core_block.id.clone(),
                    content: content.get("content").and_then(|v| v.as_str()).unwrap_or("").to_string(),
                    metadata: core_block.metadata.clone().map(|s| serde_json::from_str(&s).unwrap_or(serde_json::Value::Null)),
                    order: core_block.order,
                    is_visible: core_block.is_visible,
                }}))
            }},
        }}
    }}
    
    pub fn from_core_blocks(core_blocks: &[atomo_core::ContentBlock]) -> Result<Vec<Self>, Box<dyn std::error::Error>> {{
        core_blocks.iter().map(|block| Self::from_core_block(block)).collect()
    }}
}}

"#))
    }
    
    /// Generate platform models (AuditLogEntry, PlatformUser, UserSession)
    fn generate_platform_models(&self) -> Result<String> {
        Ok(format!(
            r#"/// Platform User model
#[derive(Debug, Clone, Serialize, Deserialize, async_graphql::SimpleObject)]
pub struct PlatformUser {{
    pub id: String,
    pub email: String,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub role: String,
    pub is_active: bool,
    pub last_login_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}}

/// Database row type for PlatformUser
#[derive(sqlx::FromRow, Debug, Clone)]
pub struct PlatformUserRow {{
    pub id: String,
    pub email: String,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub role: String,
    pub is_active: bool,
    pub last_login_at: Option<DateTime<Utc>>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}}

impl From<PlatformUserRow> for PlatformUser {{
    fn from(row: PlatformUserRow) -> Self {{
        Self {{
            id: row.id,
            email: row.email,
            first_name: row.first_name,
            last_name: row.last_name,
            role: row.role,
            is_active: row.is_active,
            last_login_at: row.last_login_at,
            created_at: row.created_at,
            updated_at: row.updated_at,
        }}
    }}
}}

/// User Session model
#[derive(Debug, Clone, Serialize, Deserialize, async_graphql::SimpleObject)]
pub struct UserSession {{
    pub id: String,
    pub user_id: String,
    pub expires_at: DateTime<Utc>,
    pub ip_address: Option<String>,
    pub user_agent: Option<String>,
    pub created_at: DateTime<Utc>,
}}

/// Database row type for UserSession
#[derive(sqlx::FromRow, Debug, Clone)]
pub struct UserSessionRow {{
    pub id: String,
    pub user_id: String,
    pub token: String,
    pub expires_at: DateTime<Utc>,
    pub ip_address: Option<String>,
    pub user_agent: Option<String>,
    pub created_at: DateTime<Utc>,
}}

impl From<UserSessionRow> for UserSession {{
    fn from(row: UserSessionRow) -> Self {{
        Self {{
            id: row.id,
            user_id: row.user_id,
            expires_at: row.expires_at,
            ip_address: row.ip_address,
            user_agent: row.user_agent,
            created_at: row.created_at,
        }}
    }}
}}

/// Audit Log Entry model
#[derive(Debug, Clone, Serialize, Deserialize, async_graphql::SimpleObject)]
pub struct AuditLogEntry {{
    pub id: String,
    pub entity_id: String,
    pub entity_type: String,
    pub operation: String,
    pub user_id: Option<String>,
    pub changes: Option<serde_json::Value>,
    pub metadata: Option<serde_json::Value>,
    pub timestamp: DateTime<Utc>,
}}

/// Database row type for AuditLogEntry
#[derive(sqlx::FromRow, Debug, Clone)]
pub struct AuditLogEntryRow {{
    pub id: String,
    pub entity_id: String,
    pub entity_type: String,
    pub operation: String,
    pub user_id: Option<String>,
    pub changes: Option<String>,
    pub metadata: Option<String>,
    pub timestamp: DateTime<Utc>,
}}

impl From<AuditLogEntryRow> for AuditLogEntry {{
    fn from(row: AuditLogEntryRow) -> Self {{
        Self {{
            id: row.id,
            entity_id: row.entity_id,
            entity_type: row.entity_type,
            operation: row.operation,
            user_id: row.user_id,
            changes: row.changes.and_then(|s| serde_json::from_str(&s).ok()),
            metadata: row.metadata.and_then(|s| serde_json::from_str(&s).ok()),
            timestamp: row.timestamp,
        }}
    }}
}}

"#))
    }
    
    /// Convert camelCase to snake_case for database field names
    fn camel_to_snake_case(&self, input: &str) -> String {
        let mut result = String::new();
        let mut chars = input.chars().peekable();
        
        while let Some(ch) = chars.next() {
            if ch.is_uppercase() && !result.is_empty() {
                result.push('_');
            }
            result.push(ch.to_lowercase().next().unwrap());
        }
        
        result
    }
    
    /// Generate basic model type
    fn generate_model_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        let mut fields = Vec::new();
        
        for (field_name, field) in &model.fields {
            let field_type = self.convert_field_type(&field.field_type, field.optional);
            
            fields.push(format!("    pub {}: {}", field_name, field_type));
        }
        
        let fields_str = fields.join(",\n");
        
        Ok(format!(
            r#"/// {model_name} entity
#[derive(SimpleObject, Debug, Clone)]
pub struct {model_name} {{
{fields_str},
}}

"#,
            model_name = model_name,
            fields_str = fields_str,
        ))
    }
    
    /// Generate wrapper type for Block types to avoid orphan rule violations
    fn generate_block_wrapper_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let mut fields = Vec::new();
        
        for (field_name, field) in &model.fields {
            let field_type = self.convert_field_type(&field.field_type, field.optional);
            fields.push(format!("    pub {}: {}", field_name, field_type));
        }
        
        let fields_str = fields.join(",\n");
        let core_type = format!("atomo_core::{}", model_name);
        
        // Generate specific field mappings based on block type
        let (from_fields_str, to_fields_str) = self.generate_block_field_mappings(model_name, &model.fields);
        
        Ok(format!(
            r#"/// {model_name} GraphQL wrapper
#[derive(SimpleObject, Debug, Clone)]
pub struct {model_name} {{
{fields_str},
}}

impl From<{core_type}> for {model_name} {{
    fn from(core: {core_type}) -> Self {{
        Self {{
{from_fields_str},
        }}
    }}
}}

impl From<{model_name}> for {core_type} {{
    fn from(wrapper: {model_name}) -> Self {{
        Self {{
{to_fields_str},
        }}
    }}
}}

"#,
            model_name = model_name,
            core_type = core_type,
            fields_str = fields_str,
            from_fields_str = from_fields_str,
            to_fields_str = to_fields_str,
        ))
    }
    
    /// Generate field mappings for Block types
    fn generate_block_field_mappings(&self, model_name: &str, fields: &std::collections::HashMap<String, Field>) -> (String, String) {
        let mut from_fields = Vec::new();
        let mut to_fields = Vec::new();
        
        for (field_name, field) in fields {
            match field_name.as_str() {
                // For optional string fields that need special handling
                "text" if field.optional => {
                    from_fields.push(format!("            {}: core.{}.unwrap_or_default()", field_name, field_name));
                    to_fields.push(format!("            {}: wrapper.{}", field_name, field_name));
                },
                // For required string fields  
                "text" => {
                    from_fields.push(format!("            {}: core.{}", field_name, field_name));
                    to_fields.push(format!("            {}: wrapper.{}", field_name, field_name));
                },
                // Handle other fields normally
                _ => {
                    from_fields.push(format!("            {}: core.{}", field_name, field_name));
                    to_fields.push(format!("            {}: wrapper.{}", field_name, field_name));
                }
            }
        }
        
        (from_fields.join(",\n"), to_fields.join(",\n"))
    }
    
    /// Generate database row type for sqlx
    fn generate_row_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        let mut fields = Vec::new();
        
        for (field_name, field) in &model.fields {
            let db_field_name = self.camel_to_snake_case(field_name);
            let field_type = self.convert_field_type_for_db(&field.field_type, field.optional);
            
            fields.push(format!("    pub {}: {}", db_field_name, field_type));
        }
        
        let fields_str = fields.join(",\n");
        
        // Generate From implementation
        let mut from_fields = Vec::new();
        for (field_name, field) in &model.fields {
            let db_field_name = self.camel_to_snake_case(field_name);
            
            // Handle BigDecimal to f64 conversion for numeric fields
            let conversion = match &field.field_type {
                FieldType::Number if field.optional => {
                    format!("            {}: row.{}.map(|v| v.to_string().parse::<f64>().unwrap_or(0.0))", field_name, db_field_name)
                },
                FieldType::Number => {
                    format!("            {}: row.{}.to_string().parse::<f64>().unwrap_or(0.0)", field_name, db_field_name)
                },
                FieldType::Blocks if field.optional => {
                    format!("            {}: row.{}.as_ref().and_then(|v| serde_json::from_value(v.clone()).ok()).unwrap_or_default()", field_name, db_field_name)
                },
                FieldType::Blocks => {
                    format!("            {}: serde_json::from_value(row.{}).unwrap_or_default()", field_name, db_field_name)
                },
                FieldType::Array(inner) => {
                    match inner.as_ref() {
                        FieldType::Custom(name) if name == "ContentBlock" || name.contains("Block") => {
                            if field.optional {
                                format!("            {}: row.{}.as_ref().and_then(|v| serde_json::from_value(v.clone()).ok()).unwrap_or_default()", field_name, db_field_name)
                            } else {
                                format!("            {}: serde_json::from_value(row.{}).unwrap_or_default()", field_name, db_field_name)
                            }
                        },
                        _ => {
                            if field.optional {
                                format!("            {}: row.{}.as_ref().and_then(|v| serde_json::from_value(v.clone()).ok()).unwrap_or_default()", field_name, db_field_name)
                            } else {
                                format!("            {}: serde_json::from_value(row.{}).unwrap_or_default()", field_name, db_field_name)
                            }
                        }
                    }
                },
                FieldType::Custom(_custom_type) if field.optional => {
                    format!("            {}: row.{}.map(|s| s.parse().unwrap_or_default())", field_name, db_field_name)
                },
                FieldType::Custom(_custom_type) => {
                    format!("            {}: row.{}.parse().unwrap_or_default()", field_name, db_field_name)
                },
                _ => {
                    format!("            {}: row.{}", field_name, db_field_name)
                }
            };
            
            from_fields.push(conversion);
        }
        let from_fields_str = from_fields.join(",\n");
        
        Ok(format!(
            r#"/// Database row type for {model_name}
#[derive(sqlx::FromRow, Debug, Clone)]
pub struct {model_name}Row {{
{fields_str},
}}

impl From<{model_name}Row> for {model_name} {{
    fn from(row: {model_name}Row) -> Self {{
        Self {{
{from_fields_str},
        }}
    }}
}}

"#,
            model_name = model_name,
            fields_str = fields_str,
            from_fields_str = from_fields_str,
        ))
    }
    
    /// Generate row type for Block types - delegate to core types
    fn generate_block_row_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let core_type = format!("atomo_core::{}", model_name);
        
        Ok(format!(
            r#"/// Database row type for {model_name} (delegated to core type)
pub type {model_name}Row = {core_type};

impl From<{model_name}Row> for {model_name} {{
    fn from(row: {model_name}Row) -> Self {{
        Self::from(row)
    }}
}}

"#,
            model_name = model_name,
            core_type = core_type,
        ))
    }
    
    /// Generate boolean expression type for filtering (Hasura v2 style)
    fn generate_bool_exp_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let mut fields = Vec::new();
        
        // Add logical operators with GraphQL field renames
        fields.push(format!("    #[graphql(name = \"_and\")]\n    pub and: Option<Vec<{model_name}BoolExp>>"));
        fields.push(format!("    #[graphql(name = \"_or\")]\n    pub or: Option<Vec<{model_name}BoolExp>>"));
        fields.push(format!("    #[graphql(name = \"_not\")]\n    pub not: Option<Box<{model_name}BoolExp>>"));
        
        // Add field-specific filters using snake_case names for database, camelCase for GraphQL
        for (field_name, field) in &model.fields {
            let snake_case_name = self.camel_to_snake_case(field_name);
            let comparison_type = self.get_field_comparison_type(&field.field_type);
            
            if snake_case_name != *field_name {
                // If the field name changes from camelCase to snake_case, add GraphQL rename
                fields.push(format!("    #[graphql(name = \"{}\")]\n    pub {}: Option<{}>", field_name, snake_case_name, comparison_type));
            } else {
                fields.push(format!("    pub {}: Option<{}>", snake_case_name, comparison_type));
            }
        }
        
        let fields_str = fields.join(",\n");
        
        Ok(format!(
            r#"/// Boolean expression for filtering {model_name}
#[derive(InputObject, Debug, Clone, Serialize, Deserialize)]
pub struct {model_name}BoolExp {{
{fields_str},
}}

"#,
            model_name = model_name,
            fields_str = fields_str,
        ))
    }
    
    /// Generate order by type (Hasura v2 style)
    fn generate_order_by_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let mut fields = Vec::new();
        
        // Use GraphQL field renames to maintain camelCase for GraphQL but snake_case for Rust
        for (field_name, _) in &model.fields {
            let snake_case_name = self.camel_to_snake_case(field_name);
            
            if snake_case_name != *field_name {
                // If the field name changes from camelCase to snake_case, add GraphQL rename
                fields.push(format!("    #[graphql(name = \"{}\")]\n    pub {}: Option<OrderBy>", field_name, snake_case_name));
            } else {
                fields.push(format!("    pub {}: Option<OrderBy>", snake_case_name));
            }
        }
        
        let fields_str = fields.join(",\n");
        
        Ok(format!(
            r#"/// Order by input for {model_name}
#[derive(InputObject, Debug, Clone, Serialize, Deserialize)]
pub struct {model_name}OrderBy {{
{fields_str},
}}

"#,
            model_name = model_name,
            fields_str = fields_str,
        ))
    }
    
    /// Generate select column enum
    fn generate_select_column_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let mut variants = Vec::new();
        
        // Use snake_case field names for Hasura v2 compatibility
        for (field_name, _) in &model.fields {
            let snake_case_name = self.camel_to_snake_case(field_name);
            variants.push(snake_case_name);
        }
        
        let variants_str = variants.join(",\n    ");
        
        Ok(format!(
            r#"/// Select columns for {model_name}
#[derive(Enum, Debug, Clone, Copy, PartialEq, Eq)]
pub enum {model_name}SelectColumn {{
    {variants_str},
}}

"#,
            model_name = model_name,
            variants_str = variants_str,
        ))
    }
    
    /// Generate insert input type
    fn generate_insert_input_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let mut fields = Vec::new();
        
        for (field_name, field) in &model.fields {
            // Skip auto-generated fields
            if field_name == "id" || field_name == "createdAt" || field_name == "updatedAt" {
                continue;
            }
            
            // Use snake_case field names for Hasura v2 compatibility
            let snake_case_name = self.camel_to_snake_case(field_name);
            let field_type = self.convert_field_type_for_input(&field.field_type, false); // Get base type without Option
            fields.push(format!("    pub {}: Option<{}>", snake_case_name, field_type));
        }
        
        let fields_str = fields.join(",\n");
        
        Ok(format!(
            r#"/// Insert input for {model_name}
#[derive(InputObject, Debug, Clone)]
pub struct {model_name}InsertInput {{
{fields_str},
}}

"#,
            model_name = model_name,
            fields_str = fields_str,
        ))
    }
    
    /// Generate set input type for updates
    fn generate_set_input_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let mut fields = Vec::new();
        
        for (field_name, field) in &model.fields {
            // Skip id and auto-generated fields for updates
            if field_name == "id" || field_name == "createdAt" {
                continue;
            }
            
            // Use snake_case field names for Hasura v2 compatibility
            let snake_case_name = self.camel_to_snake_case(field_name);
            let field_type = self.convert_field_type_for_input(&field.field_type, false); // Get base type without Option
            fields.push(format!("    pub {}: Option<{}>", snake_case_name, field_type));
        }
        
        let fields_str = fields.join(",\n");
        
        Ok(format!(
            r#"/// Set input for updating {model_name}
#[derive(InputObject, Debug, Clone)]
pub struct {model_name}SetInput {{
{fields_str},
}}

"#,
            model_name = model_name,
            fields_str = fields_str,
        ))
    }
    
    /// Generate primary key columns input
    fn generate_pk_columns_input_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        Ok(format!(
            r#"/// Primary key columns input for {model_name}
#[derive(InputObject, Debug, Clone)]
pub struct {model_name}PkColumnsInput {{
    pub id: ID,
}}

"#,
            model_name = model_name,
        ))
    }
    
    /// Generate on conflict type
    fn generate_on_conflict_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        Ok(format!(
            r#"/// On conflict input for {model_name}
#[derive(InputObject, Debug, Clone)]
pub struct {model_name}OnConflict {{
    pub constraint: {model_name}Constraint,
    pub update_columns: Vec<{model_name}UpdateColumn>,
    pub where_: Option<{model_name}BoolExp>,
}}

/// Constraint enum for {model_name}
#[derive(Enum, Debug, Clone, Copy, PartialEq, Eq)]
pub enum {model_name}Constraint {{
    {model_name}Pkey,
}}

/// Update column enum for {model_name}
#[derive(Enum, Debug, Clone, Copy, PartialEq, Eq)]
pub enum {model_name}UpdateColumn {{
    // Add update columns based on fields
    Id,
    CreatedAt,
    UpdatedAt,
}}

"#,
            model_name = model_name,
        ))
    }
    
    /// Generate mutation response type
    fn generate_mutation_response_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        Ok(format!(
            r#"/// Mutation response for {model_name}
#[derive(SimpleObject, Debug, Clone)]
pub struct {model_name}MutationResponse {{
    pub affected_rows: i32,
    pub returning: Vec<{model_name}>,
}}

"#,
            model_name = model_name,
        ))
    }
    
    /// Generate aggregate types
    fn generate_aggregate_types(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        Ok(format!(
            r#"/// Aggregate type for {model_name}
#[derive(SimpleObject, Debug, Clone)]
pub struct {model_name}Aggregate {{
    pub aggregate: Option<{model_name}AggregateFields>,
    pub nodes: Vec<{model_name}>,
}}

/// Aggregate fields for {model_name}
#[derive(SimpleObject, Debug, Clone)]
pub struct {model_name}AggregateFields {{
    pub count: Option<i32>,
    // Add more aggregate fields like sum, avg, max, min as needed
}}

"#,
            model_name = model_name,
        ))
    }
    
    /// Generate comparison operators
    fn generate_comparison_operators(&self) -> String {
        format!(r#"/// Order by enum
#[derive(Enum, Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum OrderBy {{
    Asc,
    AscNullsFirst,
    AscNullsLast,
    Desc,
    DescNullsFirst,
    DescNullsLast,
}}

/// String comparison expression
#[derive(InputObject, Debug, Clone, Serialize, Deserialize)]
pub struct StringComparisonExp {{
    #[graphql(name = "_eq")]
    pub _eq: Option<String>,
    #[graphql(name = "_neq")]
    pub _neq: Option<String>,
    #[graphql(name = "_gt")]
    pub _gt: Option<String>,
    #[graphql(name = "_gte")]
    pub _gte: Option<String>,
    #[graphql(name = "_lt")]
    pub _lt: Option<String>,
    #[graphql(name = "_lte")]
    pub _lte: Option<String>,
    #[graphql(name = "_like")]
    pub _like: Option<String>,
    #[graphql(name = "_ilike")]
    pub _ilike: Option<String>,
    #[graphql(name = "_similar")]
    pub _similar: Option<String>,
    #[graphql(name = "_regex")]
    pub _regex: Option<String>,
    #[graphql(name = "_iregex")]
    pub _iregex: Option<String>,
    #[graphql(name = "_in")]
    pub _in: Option<Vec<String>>,
    #[graphql(name = "_nin")]
    pub _nin: Option<Vec<String>>,
    #[graphql(name = "_is_null")]
    pub _is_null: Option<bool>,
}}

/// Integer comparison expression
#[derive(InputObject, Debug, Clone, Serialize, Deserialize)]
pub struct IntComparisonExp {{
    #[graphql(name = "_eq")]
    pub _eq: Option<i32>,
    #[graphql(name = "_neq")]
    pub _neq: Option<i32>,
    #[graphql(name = "_gt")]
    pub _gt: Option<i32>,
    #[graphql(name = "_gte")]
    pub _gte: Option<i32>,
    #[graphql(name = "_lt")]
    pub _lt: Option<i32>,
    #[graphql(name = "_lte")]
    pub _lte: Option<i32>,
    #[graphql(name = "_in")]
    pub _in: Option<Vec<i32>>,
    #[graphql(name = "_nin")]
    pub _nin: Option<Vec<i32>>,
    #[graphql(name = "_is_null")]
    pub _is_null: Option<bool>,
}}

/// Float comparison expression
#[derive(InputObject, Debug, Clone, Serialize, Deserialize)]
pub struct FloatComparisonExp {{
    #[graphql(name = "_eq")]
    pub _eq: Option<f64>,
    #[graphql(name = "_neq")]
    pub _neq: Option<f64>,
    #[graphql(name = "_gt")]
    pub _gt: Option<f64>,
    #[graphql(name = "_gte")]
    pub _gte: Option<f64>,
    #[graphql(name = "_lt")]
    pub _lt: Option<f64>,
    #[graphql(name = "_lte")]
    pub _lte: Option<f64>,
    #[graphql(name = "_in")]
    pub _in: Option<Vec<f64>>,
    #[graphql(name = "_nin")]
    pub _nin: Option<Vec<f64>>,
    #[graphql(name = "_is_null")]
    pub _is_null: Option<bool>,
}}

/// Boolean comparison expression
#[derive(InputObject, Debug, Clone, Serialize, Deserialize)]
pub struct BooleanComparisonExp {{
    #[graphql(name = "_eq")]
    pub _eq: Option<bool>,
    #[graphql(name = "_neq")]
    pub _neq: Option<bool>,
    #[graphql(name = "_is_null")]
    pub _is_null: Option<bool>,
}}

/// DateTime comparison expression
#[derive(InputObject, Debug, Clone, Serialize, Deserialize)]
pub struct DateTimeComparisonExp {{
    #[graphql(name = "_eq")]
    pub _eq: Option<DateTime<Utc>>,
    #[graphql(name = "_neq")]
    pub _neq: Option<DateTime<Utc>>,
    #[graphql(name = "_gt")]
    pub _gt: Option<DateTime<Utc>>,
    #[graphql(name = "_gte")]
    pub _gte: Option<DateTime<Utc>>,
    #[graphql(name = "_lt")]
    pub _lt: Option<DateTime<Utc>>,
    #[graphql(name = "_lte")]
    pub _lte: Option<DateTime<Utc>>,
    #[graphql(name = "_in")]
    pub _in: Option<Vec<DateTime<Utc>>>,
    #[graphql(name = "_nin")]
    pub _nin: Option<Vec<DateTime<Utc>>>,
    #[graphql(name = "_is_null")]
    pub _is_null: Option<bool>,
}}

/// ID comparison expression
#[derive(InputObject, Debug, Clone)]
pub struct IdComparisonExp {{
    #[graphql(name = "_eq")]
    pub _eq: Option<ID>,
    #[graphql(name = "_neq")]
    pub _neq: Option<ID>,
    #[graphql(name = "_in")]
    pub _in: Option<Vec<ID>>,
    #[graphql(name = "_nin")]
    pub _nin: Option<Vec<ID>>,
    #[graphql(name = "_is_null")]
    pub _is_null: Option<bool>,
}}

/// Numeric comparison expression (unified for all numeric types)
#[derive(InputObject, Debug, Clone, Serialize, Deserialize)]
pub struct NumericComparisonExp {{
    #[graphql(name = "_eq")]
    pub _eq: Option<f64>,
    #[graphql(name = "_neq")]
    pub _neq: Option<f64>,
    #[graphql(name = "_gt")]
    pub _gt: Option<f64>,
    #[graphql(name = "_gte")]
    pub _gte: Option<f64>,
    #[graphql(name = "_lt")]
    pub _lt: Option<f64>,
    #[graphql(name = "_lte")]
    pub _lte: Option<f64>,
    #[graphql(name = "_in")]
    pub _in: Option<Vec<f64>>,
    #[graphql(name = "_nin")]
    pub _nin: Option<Vec<f64>>,
    #[graphql(name = "_is_null")]
    pub _is_null: Option<bool>,
}}

/// Generic comparison expression (for flexible types)
#[derive(InputObject, Debug, Clone, Serialize, Deserialize)]
pub struct GenericComparisonExp {{
    #[graphql(name = "_eq")]
    pub _eq: Option<String>,
    #[graphql(name = "_neq")]
    pub _neq: Option<String>,
    #[graphql(name = "_in")]
    pub _in: Option<Vec<String>>,
    #[graphql(name = "_nin")]
    pub _nin: Option<Vec<String>>,
    #[graphql(name = "_is_null")]
    pub _is_null: Option<bool>,
}}

"#)
    }
    
    /// Convert field type to Rust type
    fn convert_field_type(&self, field_type: &FieldType, optional: bool) -> String {
        let base_type = match field_type {
            FieldType::String => "String".to_string(),
            FieldType::Number => "f64".to_string(),
            FieldType::Boolean => "bool".to_string(),
            FieldType::Date | FieldType::DateTime => "DateTime<Utc>".to_string(),
            FieldType::EntityId => "ID".to_string(),
            FieldType::Json => "serde_json::Value".to_string(),
            FieldType::Blocks => "Vec<ContentBlock>".to_string(),
            FieldType::Array(inner) => {
                // Check if the inner type is ContentBlock - if so, use proper union type
                match inner.as_ref() {
                    FieldType::Custom(name) if name == "ContentBlock" => "Vec<ContentBlock>".to_string(),
                    FieldType::Custom(name) if name.contains("Block") => "Vec<ContentBlock>".to_string(),
                    _ => format!("Vec<{}>", self.convert_field_type(inner, false))
                }
            },
            FieldType::Custom(name) => {
                // If it's ContentBlock, use the union type
                if name == "ContentBlock" {
                    "ContentBlock".to_string()
                } else if name.contains("Block") {
                    // For specific block types, use the wrapper types
                    name.clone()
                } else {
                    name.clone()
                }
            },
            FieldType::Reference(name) => name.clone(),
        };
        
        if optional {
            format!("Option<{}>", base_type)
        } else {
            base_type
        }
    }
    
    /// Convert field type to Rust type for input objects - use JSON for ContentBlock arrays
    fn convert_field_type_for_input(&self, field_type: &FieldType, optional: bool) -> String {
        let base_type = match field_type {
            FieldType::String => "String".to_string(),
            FieldType::Number => "f64".to_string(),
            FieldType::Boolean => "bool".to_string(),
            FieldType::Date | FieldType::DateTime => "DateTime<Utc>".to_string(),
            FieldType::EntityId => "ID".to_string(),
            FieldType::Json => "serde_json::Value".to_string(),
            FieldType::Blocks => "serde_json::Value".to_string(), // Use JSON for input
            FieldType::Array(inner) => {
                // Check if the inner type is ContentBlock - for input use JSON
                match inner.as_ref() {
                    FieldType::Custom(name) if name == "ContentBlock" => "serde_json::Value".to_string(),
                    FieldType::Custom(name) if name.contains("Block") => "serde_json::Value".to_string(),
                    _ => format!("Vec<{}>", self.convert_field_type_for_input(inner, false))
                }
            },
            FieldType::Custom(name) => {
                // For input, use JSON for ContentBlock types
                if name == "ContentBlock" || name.contains("Block") {
                    "serde_json::Value".to_string()
                } else {
                    name.clone()
                }
            },
            FieldType::Reference(name) => name.clone(),
        };
        
        if optional {
            format!("Option<{}>", base_type)
        } else {
            base_type
        }
    }
    
    /// Convert field type for database row
    fn convert_field_type_for_db(&self, field_type: &FieldType, optional: bool) -> String {
        let base_type = match field_type {
            FieldType::String => "String".to_string(),
            FieldType::Number => "sqlx::types::BigDecimal".to_string(),
            FieldType::Boolean => "bool".to_string(),
            FieldType::Date | FieldType::DateTime => "DateTime<Utc>".to_string(),
            FieldType::EntityId => "String".to_string(),
            FieldType::Json => "serde_json::Value".to_string(),
            FieldType::Blocks => "serde_json::Value".to_string(),
            // Store arrays as JSONB in database for better compatibility
            FieldType::Array(_) => "serde_json::Value".to_string(),
            FieldType::Custom(_) => "String".to_string(), // Store custom types as strings in DB
            FieldType::Reference(_) => "String".to_string(), // Store references as strings in DB
        };
        
        if optional {
            format!("Option<{}>", base_type)
        } else {
            base_type
        }
    }
    
    /// Generate inc input type for numeric operations
    fn generate_inc_input_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let mut fields = Vec::new();
        
        for (field_name, field) in &model.fields {
            if matches!(field.field_type, FieldType::Number) {
                fields.push(format!("    pub {}: Option<i32>", field_name));
            }
        }
        
        if fields.is_empty() {
            fields.push("    pub _placeholder: Option<String>".to_string());
        }
        
        let fields_str = fields.join(",\n");
        
        Ok(format!(
            r#"/// Inc input for {model_name}
#[derive(InputObject, Debug, Clone)]
pub struct {model_name}IncInput {{
{fields_str},
}}

"#,
            model_name = model_name,
            fields_str = fields_str,
        ))
    }
    
    /// Generate append input type
    fn generate_append_input_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        Ok(format!(
            r#"/// Append input for {model_name}
#[derive(InputObject, Debug, Clone)]
pub struct {model_name}AppendInput {{
    pub _placeholder: Option<String>,
}}

"#,
            model_name = model_name,
        ))
    }
    
    /// Generate prepend input type
    fn generate_prepend_input_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        Ok(format!(
            r#"/// Prepend input for {model_name}
#[derive(InputObject, Debug, Clone)]
pub struct {model_name}PrependInput {{
    pub _placeholder: Option<String>,
}}

"#,
            model_name = model_name,
        ))
    }
    
    /// Generate delete key input type
    fn generate_delete_key_input_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        Ok(format!(
            r#"/// Delete key input for {model_name}
#[derive(InputObject, Debug, Clone)]
pub struct {model_name}DeleteKeyInput {{
    pub _placeholder: Option<String>,
}}

"#,
            model_name = model_name,
        ))
    }
    
    /// Generate delete elem input type
    fn generate_delete_elem_input_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        Ok(format!(
            r#"/// Delete elem input for {model_name}
#[derive(InputObject, Debug, Clone)]
pub struct {model_name}DeleteElemInput {{
    pub _placeholder: Option<String>,
}}

"#,
            model_name = model_name,
        ))
    }
    
    /// Generate delete at path input type
    fn generate_delete_at_path_input_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        Ok(format!(
            r#"/// Delete at path input for {model_name}
#[derive(InputObject, Debug, Clone)]
pub struct {model_name}DeleteAtPathInput {{
    pub _placeholder: Option<String>,
}}

"#,
            model_name = model_name,
        ))
    }
    
    /// Generate aggregate type for Hasura v2 style queries
    fn generate_aggregate_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        Ok(format!(
            r#"/// {model_name} aggregate type
#[derive(SimpleObject, Clone, Debug)]
pub struct {model_name}Aggregate {{
    pub aggregate: Option<{model_name}AggregateFields>,
    pub nodes: Vec<{model_name}>,
}}

"#,
            model_name = model_name,
        ))
    }
    
    /// Generate aggregate fields type for Hasura v2 style queries
    fn generate_aggregate_fields_type(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        
        Ok(format!(
            r#"/// {model_name} aggregate fields type
#[derive(SimpleObject, Clone, Debug)]
pub struct {model_name}AggregateFields {{
    pub count: Option<i32>,
}}

"#,
            model_name = model_name,
        ))
    }
    
    /// Generate GraphQL schema definition (SDL) for IDE tools
    pub fn generate_graphql_schema_definition(&self, models: &[Model]) -> Result<String> {
        let mut schema = String::new();
        
        // Header comment
        schema.push_str("# Auto-generated GraphQL Schema Definition\n");
        schema.push_str("# This file is for IDE support and GraphQL tooling\n\n");
        
        // Generate scalar definitions
        schema.push_str("scalar DateTime\n");
        schema.push_str("scalar UUID\n");
        schema.push_str("scalar JSON\n\n");
        
        // Generate comparison expression types (Hasura v2 style)
        schema.push_str(&self.generate_comparison_types_definition()?);
        
        // Generate enum types
        for model in models {
            if model.fields.contains_key("_enum_type") {
                schema.push_str(&self.generate_graphql_enum_definition(model)?);
            }
        }
        
        // Generate object types
        for model in models {
            if !model.fields.contains_key("_enum_type") {
                schema.push_str(&self.generate_graphql_object_definition(model)?);
                schema.push_str(&self.generate_graphql_input_definition(model)?);
                schema.push_str(&self.generate_graphql_bool_exp_definition(model)?);
                schema.push_str(&self.generate_graphql_order_by_definition(model)?);
            }
        }
        
        // Generate root Query and Mutation types
        schema.push_str(&self.generate_graphql_root_types(models)?);
        
        Ok(schema)
    }

    /// Generate GraphQL schema definition with unified operation definitions
    /// This ensures 100% consistency between schema and runtime
    pub fn generate_graphql_schema_with_operations(&self, models: &[Model], operation_definitions: &OperationDefinitions) -> Result<String> {
        let mut schema = String::new();
        
        // Header comment
        schema.push_str("# Auto-generated GraphQL Schema Definition (Schema-First)\n");
        schema.push_str("# Generated with unified operation definitions for 100% consistency\n\n");
        
        // Generate scalar definitions
        schema.push_str("scalar DateTime\n");
        schema.push_str("scalar UUID\n");
        schema.push_str("scalar JSON\n\n");
        
        // Generate comparison expression types using unified definitions
        schema.push_str(&self.generate_comparison_types_with_operations(operation_definitions)?);
        
        // Generate enum types
        for model in models {
            if model.fields.contains_key("_enum_type") {
                schema.push_str(&self.generate_graphql_enum_definition(model)?);
            }
        }
        
        // Generate object types
        for model in models {
            if !model.fields.contains_key("_enum_type") {
                schema.push_str(&self.generate_graphql_object_definition(model)?);
                schema.push_str(&self.generate_graphql_input_definition(model)?);
                schema.push_str(&self.generate_graphql_bool_exp_definition(model)?);
                schema.push_str(&self.generate_graphql_order_by_definition(model)?);
            }
        }
        
        // Generate root Query and Mutation types
        schema.push_str(&self.generate_graphql_root_types(models)?);
        
        Ok(schema)
    }
    
    /// Generate GraphQL enum definition
    fn generate_graphql_enum_definition(&self, model: &Model) -> Result<String> {
        let enum_name = &model.name;
        let enum_values = match enum_name.as_str() {
            // Platform core should not have knowledge of specific business domain enum values
            // All domain-specific enums should be defined in their respective services
            _ => vec!["VALUE1", "VALUE2", "VALUE3"],
        };
        
        let mut result = format!("enum {} {{\n", enum_name);
        for value in enum_values {
            result.push_str(&format!("  {}\n", value));
        }
        result.push_str("}\n\n");
        
        Ok(result)
    }
    
    /// Generate GraphQL object type definition
    fn generate_graphql_object_definition(&self, model: &Model) -> Result<String> {
        let mut result = format!("type {} {{\n", model.name);
        
        for (field_name, field) in &model.fields {
            let graphql_type = self.map_field_to_graphql_type(&field.field_type);
            let non_null = if !field.optional { "!" } else { "" };
            result.push_str(&format!("  {}: {}{}\n", field_name, graphql_type, non_null));
        }
        
        result.push_str("}\n\n");
        Ok(result)
    }
    
    /// Generate GraphQL input type definition
    fn generate_graphql_input_definition(&self, model: &Model) -> Result<String> {
        let mut result = format!("input {}Input {{\n", model.name);
        
        for (field_name, field) in &model.fields {
            if field_name == "id" { continue; } // Skip ID in input
            
            let graphql_type = self.map_field_to_graphql_type(&field.field_type);
            result.push_str(&format!("  {}: {}\n", field_name, graphql_type));
        }
        
        result.push_str("}\n\n");
        Ok(result)
    }
    
    /// Generate GraphQL BoolExp definition
    fn generate_graphql_bool_exp_definition(&self, model: &Model) -> Result<String> {
        let mut result = format!("input {}BoolExp {{\n", model.name);
        
        result.push_str(&format!("  _and: [{}BoolExp!]\n", model.name));
        result.push_str(&format!("  _or: [{}BoolExp!]\n", model.name));
        result.push_str(&format!("  _not: {}BoolExp\n", model.name));
        
        for (field_name, field) in &model.fields {
            let comparison_type = self.get_field_comparison_type(&field.field_type);
            result.push_str(&format!("  {}: {}\n", field_name, comparison_type));
        }
        
        result.push_str("}\n\n");
        Ok(result)
    }
    
    /// Generate GraphQL OrderBy definition
    fn generate_graphql_order_by_definition(&self, model: &Model) -> Result<String> {
        let mut result = format!("input {}OrderBy {{\n", model.name);
        
        for (field_name, _) in &model.fields {
            result.push_str(&format!("  {}: OrderByDirection\n", field_name));
        }
        
        result.push_str("}\n\n");
        
        // Add OrderByDirection enum if not already added
        if !result.contains("enum OrderByDirection") {
            result.push_str("enum OrderByDirection {\n  ASC\n  DESC\n}\n\n");
        }
        
        Ok(result)
    }
    
    /// Generate root Query and Mutation types
    fn generate_graphql_root_types(&self, models: &[Model]) -> Result<String> {
        let mut result = String::new();
        
        // Query type
        result.push_str("type Query {\n");
        for model in models {
            if !model.fields.contains_key("_enum_type") {
                let model_name_lower = model.name.to_lowercase();
                let model_name_plural = format!("{}s", model_name_lower);
                
                result.push_str(&format!(
                    "  {}(where: {}BoolExp, orderBy: [{}OrderBy!]): [{}!]!\n",
                    model_name_plural, model.name, model.name, model.name
                ));
                
                result.push_str(&format!(
                    "  {}ById(id: UUID!): {}\n",
                    model_name_lower, model.name
                ));
            }
        }
        result.push_str("}\n\n");
        
        // Mutation type
        result.push_str("type Mutation {\n");
        for model in models {
            if !model.fields.contains_key("_enum_type") {
                result.push_str(&format!(
                    "  insert{}(object: {}Input!): {}!\n",
                    model.name, model.name, model.name
                ));
                
                result.push_str(&format!(
                    "  update{}(id: UUID!, object: {}Input!): {}!\n",
                    model.name, model.name, model.name
                ));
                
                result.push_str(&format!(
                    "  delete{}(id: UUID!): Boolean!\n",
                    model.name
                ));
            }
        }
        result.push_str("}\n");
        
        Ok(result)
    }
    
    /// Map Rust type to GraphQL type
    fn map_to_graphql_type(&self, rust_type: &str) -> String {
        match rust_type {
            "String" => "String".to_string(),
            "i32" | "i64" => "Int".to_string(),
            "f32" | "f64" => "Float".to_string(),
            "bool" => "Boolean".to_string(),
            "Uuid" => "UUID".to_string(),
            "DateTime<Utc>" => "DateTime".to_string(),
            "serde_json::Value" => "JSON".to_string(),
            s if s.starts_with("Vec<") => {
                let inner = s.trim_start_matches("Vec<").trim_end_matches(">");
                format!("[{}]", self.map_to_graphql_type(inner))
            },
            s if s.starts_with("Option<") => {
                let inner = s.trim_start_matches("Option<").trim_end_matches(">");
                self.map_to_graphql_type(inner)
            },
            _ => rust_type.to_string(),
        }
    }
    
    /// Map FieldType to GraphQL type for schema generation
    fn map_field_to_graphql_type(&self, field_type: &FieldType) -> String {
        match field_type {
            FieldType::String => "String".to_string(),
            FieldType::Number => "Float".to_string(),
            FieldType::Boolean => "Boolean".to_string(),
            FieldType::Date | FieldType::DateTime => "DateTime".to_string(),
            FieldType::EntityId => "UUID".to_string(),
            FieldType::Json => "JSON".to_string(),
            FieldType::Blocks => "JSON".to_string(),
            FieldType::Array(inner) => {
                format!("[{}]", self.map_field_to_graphql_type(inner))
            },
            FieldType::Custom(name) => name.clone(),
            FieldType::Reference(name) => name.clone(),
        }
    }
    
    /// Get comparison type for GraphQL BoolExp generation
    fn get_field_comparison_type(&self, field_type: &FieldType) -> String {
        match field_type {
            FieldType::String => "StringComparisonExp".to_string(),
            FieldType::Number => "NumericComparisonExp".to_string(),
            FieldType::Boolean => "BooleanComparisonExp".to_string(),
            FieldType::Date | FieldType::DateTime => "DateTimeComparisonExp".to_string(),
            FieldType::EntityId => "UUIDComparisonExp".to_string(),
            _ => "GenericComparisonExp".to_string(),
        }
    }
    
    /// Get comparison type for field (legacy - for Rust generation)
    fn get_comparison_type(&self, field_type: &str) -> String {
        match field_type {
            "String" => "StringComparisonExp".to_string(),
            "i32" | "i64" | "f32" | "f64" => "NumericComparisonExp".to_string(),
            "bool" => "BooleanComparisonExp".to_string(),
            "Uuid" => "UUIDComparisonExp".to_string(),
            "DateTime<Utc>" => "DateTimeComparisonExp".to_string(),
            _ => "GenericComparisonExp".to_string(),
        }
    }

    /// Generate comparison expression types definition for GraphQL schema
    fn generate_comparison_types_definition(&self) -> Result<String> {
        Ok(r#"# Comparison expression types (Hasura v2 compatible)

input StringComparisonExp {
  _eq: String
  _neq: String
  _gt: String
  _gte: String
  _lt: String
  _lte: String
  _like: String
  _ilike: String
  _similar: String
  _regex: String
  _iregex: String
  _in: [String!]
  _nin: [String!]
  _is_null: Boolean
}

input NumericComparisonExp {
  _eq: Float
  _neq: Float
  _gt: Float
  _gte: Float
  _lt: Float
  _lte: Float
  _in: [Float!]
  _nin: [Float!]
  _is_null: Boolean
}

input DateTimeComparisonExp {
  _eq: DateTime
  _neq: DateTime
  _gt: DateTime
  _gte: DateTime
  _lt: DateTime
  _lte: DateTime
  _in: [DateTime!]
  _nin: [DateTime!]
  _is_null: Boolean
}

input BooleanComparisonExp {
  _eq: Boolean
  _neq: Boolean
  _is_null: Boolean
}

input UUIDComparisonExp {
  _eq: UUID
  _neq: UUID
  _in: [UUID!]
  _nin: [UUID!]
  _is_null: Boolean
}

input GenericComparisonExp {
  _eq: String
  _neq: String
  _in: [String!]
  _nin: [String!]
  _is_null: Boolean
}

"#.to_string())
    }

    /// Generate comparison expression types using unified operation definitions
    /// This ensures schema and runtime use identical operation definitions
    fn generate_comparison_types_with_operations(&self, operation_definitions: &OperationDefinitions) -> Result<String> {
        let mut result = String::new();
        result.push_str("# Comparison expression types (unified operation definitions)\n\n");
        
        // Generate each comparison type using the unified definitions
        let comparison_types = [
            ("StringComparisonExp", "String", vec![FieldType::String]),
            ("NumericComparisonExp", "Float", vec![FieldType::Number]),
            ("DateTimeComparisonExp", "DateTime", vec![FieldType::Date, FieldType::DateTime]),
            ("BooleanComparisonExp", "Boolean", vec![FieldType::Boolean]),
            ("UUIDComparisonExp", "UUID", vec![FieldType::EntityId]),
            ("GenericComparisonExp", "String", vec![]), // Applies to all
        ];
        
        for (type_name, graphql_type, field_types) in comparison_types {
            result.push_str(&format!("input {} {{\n", type_name));
            
            for op in &operation_definitions.comparison_ops {
                // Check if this operation applies to this type
                let applies = field_types.is_empty() || // GenericComparisonExp applies to all
                    field_types.iter().any(|ft| op.applies_to.contains(ft));
                
                if applies {
                    match op.name.as_str() {
                        "_in" | "_nin" => {
                            result.push_str(&format!("  {}: [{}!]\n", op.name, graphql_type));
                        }
                        "_is_null" => {
                            result.push_str(&format!("  {}: Boolean\n", op.name));
                        }
                        _ => {
                            result.push_str(&format!("  {}: {}\n", op.name, graphql_type));
                        }
                    }
                }
            }
            
            result.push_str("}\n\n");
        }
        
        Ok(result)
    }

}