use anyhow::Result;
use crate::types::*;

/// GraphQL Resolver Generator
/// Generates complete GraphQL resolver implementations from TypeScript models
pub struct ResolverGenerator;

impl ResolverGenerator {
    pub fn new() -> Self {
        Self
    }
    
    /// Convert camelCase to snake_case for database field names
    fn camel_to_snake_case(&self, input: &str) -> String {
        let mut result = String::new();
        let mut chars = input.chars().peekable();
        
        while let Some(ch) = chars.next() {
            if ch.is_uppercase() && !result.is_empty() {
                result.push('_');
            }
            result.push(ch.to_lowercase().next().unwrap());
        }
        
        result
    }
    
    /// Generate complete resolver implementation for all models
    pub fn generate_resolvers(&self, models: &[Model]) -> Result<String> {
        let mut resolvers = String::new();
        
        // Add resolver header and imports
        resolvers.push_str(&self.generate_header());
        
        // Generate Query resolvers
        resolvers.push_str(&self.generate_query_resolvers(models)?);
        
        // Generate Mutation resolvers  
        resolvers.push_str(&self.generate_mutation_resolvers(models)?);
        
        // Generate resolver registration
        resolvers.push_str(&self.generate_resolver_registration(models)?);
        
        Ok(resolvers)
    }
    
    /// Generate header with imports and basic setup
    fn generate_header(&self) -> String {
        format!(r#"// Auto-generated GraphQL resolvers
// DO NOT EDIT - This file is automatically generated

use async_graphql::{{Context, Object, FieldResult, ID, EmptySubscription}};
use sqlx::PgPool;
use num_traits::ToPrimitive;

use super::models::*;

// Generated resolvers for automatic CRUD operations
pub struct Query;
pub struct Mutation;

"#)
    }
    
    /// Generate Query resolvers for all models
    fn generate_query_resolvers(&self, models: &[Model]) -> Result<String> {
        let mut query_impl = String::new();
        
        query_impl.push_str("#[Object]\nimpl Query {\n");
        
        for model in models {
            // Skip Block types and enum types
            if model.name.ends_with("Block") || model.fields.contains_key("_enum_type") {
                continue;
            }
            
            let model_name = &model.name;
            let model_lower = model_name.to_lowercase();
            
            // Generate findMany resolver with full filtering support
            query_impl.push_str(&format!(
                r#"    /// Find many {model_name} entities with advanced filtering and pagination
    async fn {model_lower}s(
        &self,
        ctx: &Context<'_>,
        where_: Option<{model_name}Filter>,
        order_by: Option<Vec<{model_name}OrderBy>>,
        first: Option<i32>,
        after: Option<String>,
        last: Option<i32>,
        before: Option<String>,
    ) -> FieldResult<{model_name}Connection> {{
        let pool = ctx.data::<PgPool>()?;
        
        // Build base query
        let mut query = format!("SELECT * FROM {model_lower}");
        let mut conditions = Vec::new();
        let mut param_count = 1;
        
        // Apply filters
        if let Some(ref filter) = where_ {{
            if let Some(id) = &filter.id {{
                conditions.push(format!("id = ${{}}", param_count));
                param_count += 1;
            }}
            
            if let Some(ids) = &filter.ids {{
                if !ids.is_empty() {{
                    let placeholders: Vec<String> = (param_count..param_count + ids.len())
                        .map(|i| format!("${{}}", i))
                        .collect();
                    conditions.push(format!("id IN ({{}})", placeholders.join(", ")));
                    param_count += ids.len();
                }}
            }}
            
{filter_conditions}
        }}
        
        if !conditions.is_empty() {{
            query.push_str(&format!(" WHERE {{}}", conditions.join(" AND ")));
        }}
        
        // Apply ordering
        let mut order_clauses = Vec::new();
        if let Some(orders) = order_by {{
            for order in orders {{
                match order {{
                    {model_name}OrderBy::CreatedAtAsc => order_clauses.push("created_at ASC".to_string()),
                    {model_name}OrderBy::CreatedAtDesc => order_clauses.push("created_at DESC".to_string()),
                    {model_name}OrderBy::UpdatedAtAsc => order_clauses.push("updated_at ASC".to_string()),
                    {model_name}OrderBy::UpdatedAtDesc => order_clauses.push("updated_at DESC".to_string()),
{order_conditions}
                }}
            }}
        }} else {{
            order_clauses.push("created_at DESC".to_string()); // Default ordering
        }}
        
        if !order_clauses.is_empty() {{
            query.push_str(&format!(" ORDER BY {{}}", order_clauses.join(", ")));
        }}
        
        // Apply pagination
        let limit = first.or(last).unwrap_or(50).min(100); // Max 100 items
        query.push_str(&format!(" LIMIT ${{}}", param_count));
        param_count += 1;
        
        if let Some(offset) = after.as_ref().or(before.as_ref()) {{
            if let Ok(_offset_num) = offset.parse::<i32>() {{
                query.push_str(&format!(" OFFSET ${{}}", param_count));
            }}
        }}
        
        // Execute query with manual parameter binding
        let mut sqlx_query = sqlx::query_as::<_, {model_name}Row>(&query);
        
        // Bind parameters in order
        if let Some(ref filter) = where_ {{
            if let Some(id) = &filter.id {{
                sqlx_query = sqlx_query.bind(id.to_string());
            }}
            
            if let Some(ids) = &filter.ids {{
                for id in ids {{
                    sqlx_query = sqlx_query.bind(id.to_string());
                }}
            }}
            
{bind_filter_params}
        }}
        
        // Bind pagination parameters
        sqlx_query = sqlx_query.bind(limit);
        if let Some(offset) = after.as_ref().or(before.as_ref()) {{
            if let Ok(offset_num) = offset.parse::<i32>() {{
                sqlx_query = sqlx_query.bind(offset_num);
            }}
        }}
        
        let entities = sqlx_query.fetch_all(pool).await?;
        
        // Convert to connection format
        let edges: Vec<{model_name}Edge> = entities
            .into_iter()
            .enumerate()
            .map(|(index, entity)| {model_name}Edge {{
                node: entity.into(),
                cursor: index.to_string(), // Simple index-based cursor
            }})
            .collect();
        
        let page_info = PageInfo {{
            has_next_page: edges.len() == limit as usize,
            has_previous_page: after.as_ref().or(before.as_ref()).is_some(),
            start_cursor: edges.first().map(|e| e.cursor.clone()),
            end_cursor: edges.last().map(|e| e.cursor.clone()),
        }};
        
        Ok({model_name}Connection {{
            edges,
            page_info,
            total_count: 0, // TODO: Implement total count query
        }})
    }}

    /// Find a single {model_name} by ID
    async fn {model_lower}(
        &self,
        ctx: &Context<'_>,
        id: ID,
    ) -> FieldResult<Option<{model_name}>> {{
        let pool = ctx.data::<PgPool>()?;
        
        let entity = sqlx::query_as::<_, {model_name}Row>(
            "SELECT * FROM {model_lower} WHERE id = $1"
        )
        .bind(id.to_string())
        .fetch_optional(pool)
        .await?;

        Ok(entity.map(|e| e.into()))
    }}
"#,
                model_name = model_name,
                model_lower = model_lower,
                filter_conditions = self.generate_filter_conditions(model)?,
                bind_filter_params = self.generate_bind_filter_params(model)?,
                order_conditions = self.generate_order_conditions(model)?,
            ));
        }
        
        query_impl.push_str("}\n\n");
        Ok(query_impl)
    }
    
    /// Generate Mutation resolvers for all models
    fn generate_mutation_resolvers(&self, models: &[Model]) -> Result<String> {
        let mut mutation_impl = String::new();
        
        mutation_impl.push_str("#[Object]\nimpl Mutation {\n");
        
        for model in models {
            // Skip Block types and enum types
            if model.name.ends_with("Block") || model.fields.contains_key("_enum_type") {
                continue;
            }
            
            let model_name = &model.name;
            let model_lower = model_name.to_lowercase();
            
            // Generate create resolver
            mutation_impl.push_str(&self.generate_create_resolver(model)?);
            
            // Generate update resolver
            mutation_impl.push_str(&self.generate_update_resolver(model)?);
            
            // Generate delete resolver
            mutation_impl.push_str(&self.generate_delete_resolver(model)?);
        }
        
        mutation_impl.push_str("}\n\n");
        Ok(mutation_impl)
    }
    
    /// Generate create resolver for a model
    fn generate_create_resolver(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let model_lower = model_name.to_lowercase();
        
        // Generate field list for INSERT
        let mut insert_fields = Vec::new();
        let mut insert_placeholders = Vec::new();
        let mut bind_statements = Vec::new();
        let mut param_count = 2; // $1 is for id
        
        for (field_name, field) in &model.fields {
            if field_name == "id" || field_name == "createdAt" || field_name == "updatedAt" {
                continue; // Skip auto-generated fields
            }
            
            // Convert camelCase to snake_case for database columns
            let db_field_name = self.camel_to_snake_case(field_name);
            insert_fields.push(db_field_name);
            insert_placeholders.push(format!("${}", param_count));
            
            match &field.field_type {
                crate::types::FieldType::String => {
                    if !field.optional {
                        bind_statements.push(format!("        .bind(input.{})", field_name));
                    } else {
                        bind_statements.push(format!("        .bind(input.{}.as_ref().map(|s| s.as_str()))", field_name));
                    }
                }
                crate::types::FieldType::Number => {
                    bind_statements.push(format!("        .bind(sqlx::types::BigDecimal::try_from(input.{}).unwrap_or_default())", field_name));
                }
                crate::types::FieldType::Boolean => {
                    bind_statements.push(format!("        .bind(input.{})", field_name));
                }
                crate::types::FieldType::Date | crate::types::FieldType::DateTime => {
                    bind_statements.push(format!("        .bind(input.{})", field_name));
                }
                crate::types::FieldType::EntityId => {
                    if !field.optional {
                        bind_statements.push(format!("        .bind(input.{})", field_name));
                    } else {
                        bind_statements.push(format!("        .bind(input.{}.as_ref().map(|s| s.as_str()))", field_name));
                    }
                }
                crate::types::FieldType::Json | crate::types::FieldType::Blocks => {
                    bind_statements.push(format!("        .bind(serde_json::to_value(&input.{}).unwrap_or(serde_json::Value::Null))", field_name));
                }
                crate::types::FieldType::Array(_) => {
                    // For arrays, wrap in sqlx::types::Json for database storage
                    if field.optional {
                        bind_statements.push(format!("        .bind(input.{}.as_ref().map(|v| sqlx::types::Json(v.clone())).unwrap_or_else(|| sqlx::types::Json(Vec::new())))", field_name));
                    } else {
                        bind_statements.push(format!("        .bind(sqlx::types::Json(input.{}.clone()))", field_name));
                    }
                }
                crate::types::FieldType::Custom(_) => {
                    // For enums, convert to string using serde JSON serialization and remove quotes
                    if !field.optional {
                        bind_statements.push(format!("        .bind(serde_json::to_string(&input.{}).unwrap_or_default().trim_matches('\"').to_string())", field_name));
                    } else {
                        bind_statements.push(format!("        .bind(input.{}.as_ref().map(|e| serde_json::to_string(e).unwrap_or_default().trim_matches('\"').to_string()))", field_name));
                    }
                }
                crate::types::FieldType::Reference(_) => {
                    // For references, treat as string
                    if !field.optional {
                        bind_statements.push(format!("        .bind(input.{})", field_name));
                    } else {
                        bind_statements.push(format!("        .bind(input.{}.as_ref().map(|s| s.as_str()))", field_name));
                    }
                }
            }
            param_count += 1;
        }
        
        let insert_fields_str = insert_fields.join(", ");
        let insert_placeholders_str = insert_placeholders.join(", ");
        let bind_statements_str = bind_statements.join("\n");
        let now_param = param_count;
        let now_param_2 = param_count + 1;
        
        // Generate field mappings for the return struct
        let mut field_mappings = Vec::new();
        for (field_name, field) in &model.fields {
            if field_name == "id" || field_name == "createdAt" || field_name == "updatedAt" || field_name == "version" {
                continue; // Skip fields already handled
            }
            
            let db_field_name = self.camel_to_snake_case(field_name);
            let rust_field_name = self.camel_to_snake_case(field_name);  // Use snake_case for Rust struct fields
            
            match &field.field_type {
                crate::types::FieldType::String => {
                    if field.optional {
                        field_mappings.push(format!("            {}: row.{}", rust_field_name, db_field_name));
                    } else {
                        field_mappings.push(format!("            {}: row.{}.clone()", rust_field_name, db_field_name));
                    }
                }
                crate::types::FieldType::Number => {
                    field_mappings.push(format!("            {}: row.{}.to_f64().unwrap_or(0.0)", rust_field_name, db_field_name));
                }
                crate::types::FieldType::Boolean => {
                    field_mappings.push(format!("            {}: row.{}", rust_field_name, db_field_name));
                }
                crate::types::FieldType::Date | crate::types::FieldType::DateTime => {
                    field_mappings.push(format!("            {}: row.{}", rust_field_name, db_field_name));
                }
                crate::types::FieldType::EntityId => {
                    if field.optional {
                        field_mappings.push(format!("            {}: row.{}", rust_field_name, db_field_name));
                    } else {
                        field_mappings.push(format!("            {}: row.{}.clone()", rust_field_name, db_field_name));
                    }
                }
                crate::types::FieldType::Json | crate::types::FieldType::Blocks => {
                    field_mappings.push(format!("            {}: row.{}.clone()", rust_field_name, db_field_name));
                }
                crate::types::FieldType::Array(_) => {
                    // For JSON arrays stored as JSONB in database, extract the inner value
                    field_mappings.push(format!("            {}: row.{}.0", rust_field_name, db_field_name));
                }
                crate::types::FieldType::Custom(_) => {
                    // For enums, parse from string value
                    if field.optional {
                        field_mappings.push(format!("            {}: row.{}.as_ref().and_then(|s| serde_json::from_str(&format!(\"\\\"{{}}\\\"\", s)).ok())", rust_field_name, db_field_name));
                    } else {
                        field_mappings.push(format!("            {}: serde_json::from_str(&format!(\"\\\"{{}}\\\"\", row.{}.as_str())).ok().unwrap_or_else(|| panic!(\"Failed to parse enum from: {{}}\", row.{}.as_str()))", rust_field_name, db_field_name, db_field_name));
                    }
                }
                crate::types::FieldType::Reference(_) => {
                    if field.optional {
                        field_mappings.push(format!("            {}: row.{}", rust_field_name, db_field_name));
                    } else {
                        field_mappings.push(format!("            {}: row.{}.clone()", rust_field_name, db_field_name));
                    }
                }
            }
        }
        
        let field_mappings_str = if field_mappings.is_empty() {
            String::new()
        } else {
            format!(",\n{}", field_mappings.join(",\n"))
        };
        
        Ok(format!(
            r#"    /// Create a new {model_name}
    async fn create_{model_lower}(
        &self,
        ctx: &Context<'_>,
        input: Create{model_name}Input,
    ) -> FieldResult<{model_name}> {{
        let pool = ctx.data::<PgPool>()?;
        
        // Generate UUID for new record
        let id = uuid::Uuid::new_v4().to_string();
        let now = chrono::Utc::now();
        
        // Insert new record and fetch it back
        let row = sqlx::query_as::<_, {model_name}Row>(
            "INSERT INTO {model_lower} (id, {insert_fields_str}, created_at, updated_at) 
             VALUES ($1, {insert_placeholders_str}, ${now_param}, ${now_param_2})
             RETURNING *"
        )
        .bind(id)
{bind_statements_str}
        .bind(now)
        .bind(now)
        .fetch_one(pool)
        .await?;
        
        // Convert database row to GraphQL model
        Ok(row.into())
    }}

"#,
            model_name = model_name,
            model_lower = model_lower,
            insert_fields_str = insert_fields_str,
            insert_placeholders_str = insert_placeholders_str,
            bind_statements_str = bind_statements_str,
            now_param = now_param,
            now_param_2 = now_param_2,
        ))
    }
    
    /// Generate update resolver for a model
    fn generate_update_resolver(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let model_lower = model_name.to_lowercase();
        
        // Generate field updates
        // Generate UPDATE statement using COALESCE to keep existing values for NULL inputs
        let mut update_fields = Vec::new();
        let mut bind_statements = Vec::new();
        let mut param_count = 1;
        
        // Always update updated_at
        update_fields.push("updated_at = $2".to_string());
        bind_statements.push("        .bind(chrono::Utc::now())".to_string());
        param_count = 3;
        
        for (field_name, field) in &model.fields {
            if field_name == "id" || field_name == "createdAt" || field_name == "updatedAt" {
                continue; // Skip non-updatable fields
            }
            
            // Convert camelCase to snake_case for database columns
            let db_field_name = self.camel_to_snake_case(field_name);
            
            // Use COALESCE to keep existing value if new value is NULL
            update_fields.push(format!("{} = COALESCE(${}, {})", db_field_name, param_count, db_field_name));
            
            match &field.field_type {
                crate::types::FieldType::String => {
                    bind_statements.push(format!("        .bind(input.data.{}.as_ref().map(|s| s.as_str()))", field_name));
                }
                crate::types::FieldType::Number => {
                    bind_statements.push(format!("        .bind(input.data.{}.map(|v| sqlx::types::BigDecimal::try_from(v).unwrap_or_default()))", field_name));
                }
                crate::types::FieldType::Boolean => {
                    bind_statements.push(format!("        .bind(input.data.{})", field_name));
                }
                crate::types::FieldType::Date | crate::types::FieldType::DateTime => {
                    bind_statements.push(format!("        .bind(input.data.{})", field_name));
                }
                crate::types::FieldType::EntityId => {
                    bind_statements.push(format!("        .bind(input.data.{}.as_ref().map(|s| s.as_str()))", field_name));
                }
                crate::types::FieldType::Json | crate::types::FieldType::Blocks => {
                    bind_statements.push(format!("        .bind(input.data.{}.as_ref().map(|v| serde_json::to_value(v).unwrap_or(serde_json::Value::Null)))", field_name));
                }
                crate::types::FieldType::Array(_) => {
                    bind_statements.push(format!("        .bind(input.data.{}.as_ref().map(|v| sqlx::types::Json(v.clone())))", field_name));
                }
                crate::types::FieldType::Custom(_) => {
                    bind_statements.push(format!("        .bind(input.data.{}.as_ref().map(|e| serde_json::to_string(e).unwrap_or_default().trim_matches('\"').to_string()))", field_name));
                }
                crate::types::FieldType::Reference(_) => {
                    bind_statements.push(format!("        .bind(input.data.{}.as_ref().map(|s| s.as_str()))", field_name));
                }
            }
            param_count += 1;
        }
        
        let update_fields_str = update_fields.join(", ");
        let bind_statements_str = bind_statements.join("\n");
        
        let update_fields_str = update_fields.join(", ");
        let bind_statements_str = bind_statements.join("\n");
        
        // Generate field mappings for the return struct (same as create)
        let mut field_mappings = Vec::new();
        for (field_name, field) in &model.fields {
            if field_name == "id" || field_name == "createdAt" || field_name == "updatedAt" || field_name == "version" {
                continue; // Skip fields already handled
            }
            
            let db_field_name = self.camel_to_snake_case(field_name);
            let rust_field_name = self.camel_to_snake_case(field_name);  // Use snake_case for Rust struct fields
            
            match &field.field_type {
                crate::types::FieldType::String => {
                    if field.optional {
                        field_mappings.push(format!("            {}: row.{}", rust_field_name, db_field_name));
                    } else {
                        field_mappings.push(format!("            {}: row.{}.clone()", rust_field_name, db_field_name));
                    }
                }
                crate::types::FieldType::Number => {
                    field_mappings.push(format!("            {}: row.{}.to_f64().unwrap_or(0.0)", rust_field_name, db_field_name));
                }
                crate::types::FieldType::Boolean => {
                    field_mappings.push(format!("            {}: row.{}", rust_field_name, db_field_name));
                }
                crate::types::FieldType::Date | crate::types::FieldType::DateTime => {
                    field_mappings.push(format!("            {}: row.{}", rust_field_name, db_field_name));
                }
                crate::types::FieldType::EntityId => {
                    if field.optional {
                        field_mappings.push(format!("            {}: row.{}", rust_field_name, db_field_name));
                    } else {
                        field_mappings.push(format!("            {}: row.{}.clone()", rust_field_name, db_field_name));
                    }
                }
                crate::types::FieldType::Json | crate::types::FieldType::Blocks => {
                    field_mappings.push(format!("            {}: row.{}.clone()", rust_field_name, db_field_name));
                }
                crate::types::FieldType::Array(_) => {
                    // For JSON arrays stored as JSONB in database, extract the inner value
                    field_mappings.push(format!("            {}: row.{}.0", rust_field_name, db_field_name));
                }
                crate::types::FieldType::Custom(_) => {
                    // For enums, parse from string value
                    if field.optional {
                        field_mappings.push(format!("            {}: row.{}.as_ref().and_then(|s| serde_json::from_str(&format!(\"\\\"{{}}\\\"\", s)).ok())", rust_field_name, db_field_name));
                    } else {
                        field_mappings.push(format!("            {}: serde_json::from_str(&format!(\"\\\"{{}}\\\"\", row.{}.as_str())).ok().unwrap_or_else(|| panic!(\"Failed to parse enum from: {{}}\", row.{}.as_str()))", rust_field_name, db_field_name, db_field_name));
                    }
                }
                crate::types::FieldType::Reference(_) => {
                    if field.optional {
                        field_mappings.push(format!("            {}: row.{}", rust_field_name, db_field_name));
                    } else {
                        field_mappings.push(format!("            {}: row.{}.clone()", rust_field_name, db_field_name));
                    }
                }
            }
        }
        
        let field_mappings_str = if field_mappings.is_empty() {
            String::new()
        } else {
            format!(",\n{}", field_mappings.join(",\n"))
        };
        
        Ok(format!(
            r#"    /// Update a {model_name}
    async fn update_{model_lower}(
        &self,
        ctx: &Context<'_>,
        input: Update{model_name}Input,
    ) -> FieldResult<{model_name}> {{
        let pool = ctx.data::<PgPool>()?;
        
        // Update only provided fields using COALESCE to keep existing values for NULL inputs
        let row = sqlx::query_as::<_, {model_name}Row>(
            "UPDATE {model_lower} SET {update_fields_str} WHERE id = $1 RETURNING *")
        .bind(input.id.as_str())
{bind_statements_str}
        .fetch_one(pool)
        .await?;
        
        // Convert database row to GraphQL model
        Ok(row.into())
    }}

"#,
            model_name = model_name,
            model_lower = model_lower,
            update_fields_str = update_fields_str,
            bind_statements_str = bind_statements_str,
        ))
    }
    
    /// Generate delete resolver for a model
    fn generate_delete_resolver(&self, model: &Model) -> Result<String> {
        let model_name = &model.name;
        let model_lower = model_name.to_lowercase();
        
        Ok(format!(
            r#"    /// Delete a {model_name}
    async fn delete_{model_lower}(
        &self,
        ctx: &Context<'_>,
        id: ID,
    ) -> FieldResult<bool> {{
        let pool = ctx.data::<PgPool>()?;
        
        let result = sqlx::query!(
            "DELETE FROM {model_lower} WHERE id = $1",
            id.as_str()
        )
        .execute(pool)
        .await?;
        
        Ok(result.rows_affected() > 0)
    }}

"#,
            model_name = model_name,
            model_lower = model_lower
        ))
    }
    
    /// Generate resolver registration code
    fn generate_resolver_registration(&self, models: &[Model]) -> Result<String> {
        let mut registration = String::new();
        
        registration.push_str(r#"/// Build the complete GraphQL schema with all resolvers
pub fn build_schema() -> async_graphql::Schema<Query, Mutation, EmptySubscription> {
    async_graphql::Schema::build(Query, Mutation, EmptySubscription)
        .finish()
}
"#);
        
        Ok(registration)
    }
    
    /// Generate filter conditions for a model
    fn generate_filter_conditions(&self, model: &Model) -> Result<String> {
        let mut conditions = Vec::new();
        
        for (field_name, field) in &model.fields {
            if field_name == "id" { continue; }
            
            let db_field_name = self.camel_to_snake_case(field_name);
            
            match &field.field_type {
                crate::types::FieldType::String => {
                    conditions.push(format!(
                        r#"            if let Some(_) = filter.{} {{
                conditions.push(format!("{} = ${{}}", param_count));
                param_count += 1;
            }}
            
            if let Some(_) = filter.{}Contains {{
                conditions.push(format!("{} ILIKE ${{}}", param_count));
                param_count += 1;
            }}"#,
                        field_name, db_field_name, field_name, db_field_name
                    ));
                }
                crate::types::FieldType::Number => {
                    conditions.push(format!(
                        r#"            if let Some(_) = filter.{} {{
                conditions.push(format!("{} = ${{}}", param_count));
                param_count += 1;
            }}
            
            if let Some(_) = filter.{}Gte {{
                conditions.push(format!("{} >= ${{}}", param_count));
                param_count += 1;
            }}
            
            if let Some(_) = filter.{}Lte {{
                conditions.push(format!("{} <= ${{}}", param_count));
                param_count += 1;
            }}"#,
                        field_name, db_field_name, field_name, db_field_name, field_name, db_field_name
                    ));
                }
                crate::types::FieldType::Boolean => {
                    conditions.push(format!(
                        r#"            if let Some(_) = filter.{} {{
                conditions.push(format!("{} = ${{}}", param_count));
                param_count += 1;
            }}"#,
                        field_name, db_field_name
                    ));
                }
                crate::types::FieldType::Date | crate::types::FieldType::DateTime => {
                    conditions.push(format!(
                        r#"            if let Some(_) = filter.{}After {{
                conditions.push(format!("{} > ${{}}", param_count));
                param_count += 1;
            }}
            
            if let Some(_) = filter.{}Before {{
                conditions.push(format!("{} < ${{}}", param_count));
                param_count += 1;
            }}"#,
                        field_name, db_field_name, field_name, db_field_name
                    ));
                }
                _ => {
                    // For other types, just basic equality
                    conditions.push(format!(
                        r#"            if let Some(_) = filter.{} {{
                conditions.push(format!("{} = ${{}}", param_count));
                param_count += 1;
            }}"#,
                        field_name, db_field_name
                    ));
                }
            }
        }
        
        // Add audit field filters
        conditions.push(r#"            if let Some(_) = filter.createdAfter {
                conditions.push(format!("created_at > ${}", param_count));
                param_count += 1;
            }
            
            if let Some(_) = filter.createdBefore {
                conditions.push(format!("created_at < ${}", param_count));
                param_count += 1;
            }
            
            if let Some(_) = filter.updatedAfter {
                conditions.push(format!("updated_at > ${}", param_count));
                param_count += 1;
            }
            
            if let Some(_) = filter.updatedBefore {
                conditions.push(format!("updated_at < ${}", param_count));
                param_count += 1;
            }"#.to_string());
        
        Ok(conditions.join("\n"))
    }
    
    /// Generate order conditions for a model
    fn generate_order_conditions(&self, model: &Model) -> Result<String> {
        let mut conditions = Vec::new();
        
        for (field_name, _field) in &model.fields {
            if field_name == "id" { continue; }
            
            let db_field_name = self.camel_to_snake_case(field_name);
            let enum_name_asc = format!("{}Asc", field_name);
            let enum_name_desc = format!("{}Desc", field_name);
            
            conditions.push(format!(
                r#"                    {}OrderBy::{} => order_clauses.push("{} ASC".to_string()),
                    {}OrderBy::{} => order_clauses.push("{} DESC".to_string()),"#,
                model.name, enum_name_asc, db_field_name,
                model.name, enum_name_desc, db_field_name
            ));
        }
        
        Ok(conditions.join("\n"))
    }
    
    fn generate_bind_filter_params(&self, model: &Model) -> Result<String> {
        let mut bindings = Vec::new();
        
        for (field_name, field) in &model.fields {
            if field_name == "id" { continue; }
            
            match &field.field_type {
                crate::types::FieldType::String => {
                    bindings.push(format!(
                        r#"            if let Some(value) = &filter.{} {{
                sqlx_query = sqlx_query.bind(value.clone());
            }}
            
            if let Some(value) = &filter.{}Contains {{
                sqlx_query = sqlx_query.bind(format!("%{{}}%", value));
            }}"#,
                        field_name, field_name
                    ));
                }
                crate::types::FieldType::Number => {
                    bindings.push(format!(
                        r#"            if let Some(value) = &filter.{} {{
                sqlx_query = sqlx_query.bind(sqlx::types::BigDecimal::try_from(*value).unwrap_or_default());
            }}
            
            if let Some(value) = &filter.{}Gte {{
                sqlx_query = sqlx_query.bind(sqlx::types::BigDecimal::try_from(*value).unwrap_or_default());
            }}
            
            if let Some(value) = &filter.{}Lte {{
                sqlx_query = sqlx_query.bind(sqlx::types::BigDecimal::try_from(*value).unwrap_or_default());
            }}"#,
                        field_name, field_name, field_name
                    ));
                }
                crate::types::FieldType::Boolean => {
                    bindings.push(format!(
                        r#"            if let Some(value) = &filter.{} {{
                sqlx_query = sqlx_query.bind(*value);
            }}"#,
                        field_name
                    ));
                }
                crate::types::FieldType::Date | crate::types::FieldType::DateTime => {
                    bindings.push(format!(
                        r#"            if let Some(value) = &filter.{}After {{
                sqlx_query = sqlx_query.bind(value.clone());
            }}
            
            if let Some(value) = &filter.{}Before {{
                sqlx_query = sqlx_query.bind(value.clone());
            }}"#,
                        field_name, field_name
                    ));
                }
                _ => {
                    bindings.push(format!(
                        r#"            if let Some(value) = &filter.{} {{
                sqlx_query = sqlx_query.bind(value.clone());
            }}"#,
                        field_name
                    ));
                }
            }
        }
        
        // Add audit field bindings
        bindings.push(r#"            if let Some(value) = &filter.createdAfter {
                sqlx_query = sqlx_query.bind(value.clone());
            }
            
            if let Some(value) = &filter.createdBefore {
                sqlx_query = sqlx_query.bind(value.clone());
            }
            
            if let Some(value) = &filter.updatedAfter {
                sqlx_query = sqlx_query.bind(value.clone());
            }
            
            if let Some(value) = &filter.updatedBefore {
                sqlx_query = sqlx_query.bind(value.clone());
            }"#.to_string());
        
        Ok(bindings.join("\n"))
    }
}
