use anyhow::Result;
use crate::types::*;

/// GraphQL Resolver Generator
/// Generates complete GraphQL resolver implementations from TypeScript models
pub struct ResolverGenerator;

impl ResolverGenerator {
    pub fn new() -> Self {
        Self
    }
    
    /// Convert camelCase to snake_case for database field names
    fn camel_to_snake_case(&self, input: &str) -> String {
        let mut result = String::new();
        let mut chars = input.chars().peekable();
        
        while let Some(ch) = chars.next() {
            if ch.is_uppercase() && !result.is_empty() {
                result.push('_');
            }
            result.push(ch.to_lowercase().next().unwrap());
        }
        
        result
    }
    
    /// Generate complete resolver implementation for all models
    pub fn generate_resolvers(&self, models: &[Model]) -> Result<String> {
        let mut resolvers = String::new();
        
        // Add resolver header and imports
        resolvers.push_str(&self.generate_header());
        
        // Generate Query resolvers
        resolvers.push_str(&self.generate_query_resolvers(models)?);
        
        // Generate Mutation resolvers  
        resolvers.push_str(&self.generate_mutation_resolvers(models)?);
        
        // Generate resolver registration
        resolvers.push_str(&self.generate_resolver_registration(models)?);
        
        Ok(resolvers)
    }
    
    /// Generate header with imports and basic setup
    fn generate_header(&self) -> String {
        format!(r#"// Auto-generated GraphQL resolvers
// DO NOT EDIT - This file is automatically generated

use async_graphql::{{Context, Object, FieldResult, ID, EmptySubscription}};
use sqlx::PgPool;

use super::models::*;

// Generated resolvers for automatic CRUD operations
pub struct Query;
pub struct Mutation;

"#)
    }
    
    /// Generate Query resolvers for all models
    fn generate_query_resolvers(&self, models: &[Model]) -> Result<String> {
        let mut query_impl = String::new();
        
        query_impl.push_str("#[Object]\nimpl Query {\n");
        
        for model in models {
            // Skip Block types and enum types
            if model.name.ends_with("Block") || model.fields.contains_key("_enum_type") {
                continue;
            }
            
            let model_name = &model.name;
            let model_lower = model_name.to_lowercase();
            
            // Generate findMany resolver
            query_impl.push_str(&format!(
                r#"    /// Find many {model_name} entities
    async fn {model_lower}s(
        &self,
        ctx: &Context<'_>,
    ) -> FieldResult<Vec<{model_name}>> {{
        let pool = ctx.data::<PgPool>()?;
        
        let entities = sqlx::query_as::<_, {model_name}>(
            "SELECT * FROM {model_lower} LIMIT 100"
        )
        .fetch_all(pool)
        .await?;
        
        Ok(entities)
    }}

    /// Find a single {model_name} by ID
    async fn {model_lower}(
        &self,
        ctx: &Context<'_>,
        id: ID,
    ) -> FieldResult<Option<{model_name}>> {{
        let pool = ctx.data::<PgPool>()?;
        
        let entity = sqlx::query_as::<_, {model_name}>(
            "SELECT * FROM {model_lower} WHERE id = $1"
        )
        .bind(id.to_string())
        .fetch_optional(pool)
        .await?;
        
        Ok(entity)
    }}
"#,
                model_name = model_name,
                model_lower = model_lower
            ));
        }
        
        query_impl.push_str("}\n\n");
        Ok(query_impl)
    }
    
    /// Generate Mutation resolvers for all models
    fn generate_mutation_resolvers(&self, models: &[Model]) -> Result<String> {
        let mut mutation_impl = String::new();
        
        mutation_impl.push_str("#[Object]\nimpl Mutation {\n");
        
        for model in models {
            // Skip Block types and enum types
            if model.name.ends_with("Block") || model.fields.contains_key("_enum_type") {
                continue;
            }
            
            let model_name = &model.name;
            let model_lower = model_name.to_lowercase();
            
            // Generate create resolver (simplified version)
            mutation_impl.push_str(&format!(
                r#"    /// Create a new {model_name}
    async fn create_{model_lower}(
        &self,
        ctx: &Context<'_>,
        _input: Create{model_name}Input,
    ) -> FieldResult<{model_name}> {{
        let _pool = ctx.data::<PgPool>()?;
        
        // TODO: Implement dynamic field insertion
        // For now, return an error
        Err("Create {model_name} not yet implemented".into())
    }}

    /// Delete a {model_name}
    async fn delete_{model_lower}(
        &self,
        ctx: &Context<'_>,
        id: ID,
    ) -> FieldResult<bool> {{
        let pool = ctx.data::<PgPool>()?;
        
        let result = sqlx::query(
            "DELETE FROM {model_lower} WHERE id = $1"
        )
        .bind(id.to_string())
        .execute(pool)
        .await?;
        
        Ok(result.rows_affected() > 0)
    }}
"#,
                model_name = model_name,
                model_lower = model_lower
            ));
        }
        
        mutation_impl.push_str("}\n\n");
        Ok(mutation_impl)
    }
    
    /// Generate resolver registration code
    fn generate_resolver_registration(&self, models: &[Model]) -> Result<String> {
        let mut registration = String::new();
        
        registration.push_str(r#"/// Build the complete GraphQL schema with all resolvers
pub fn build_schema() -> async_graphql::Schema<Query, Mutation, EmptySubscription> {
    async_graphql::Schema::build(Query, Mutation, EmptySubscription)
        .finish()
}
"#);
        
        Ok(registration)
    }
}
