//! Core Domain Traits - 业务领域的核心抽象
//!
//! This module defines the fundamental traits that all domain entities
//! and aggregates must implement in the Atomo platform.

use crate::events::DomainEvent;
use crate::types::{EntityId, StreamId, Timestamp};
use async_trait::async_trait;
use serde::{Deserialize, Serialize};

/// Core entity trait that all domain entities must implement
///
/// This trait ensures that all entities have basic identity and
/// audit capabilities required by the Atomo platform.
pub trait Entity: Send + Sync + Clone {
    /// Get the unique identifier of this entity
    fn id(&self) -> EntityId;

    /// Get the entity type name for audit logging
    fn entity_type(&self) -> &'static str;

    /// Get when this entity was created
    fn created_at(&self) -> Timestamp;

    /// Get when this entity was last updated
    fn updated_at(&self) -> Timestamp;
}

/// Aggregate root trait for event sourcing
///
/// Aggregates are the consistency boundaries in our domain model.
/// They generate events and maintain their own state.
#[async_trait]
pub trait AggregateRoot<Event>: Entity
where
    Event: DomainEvent,
{
    type Error: Send + Sync + 'static;

    /// Get the stream ID for this aggregate
    fn stream_id(&self) -> StreamId;

    /// Get all uncommitted events generated by this aggregate
    fn uncommitted_events(&self) -> &[Event];

    /// Mark all events as committed (clear uncommitted events)
    fn mark_events_as_committed(&mut self);

    /// Apply an event to this aggregate (for event replay)
    async fn apply_event(&mut self, event: &Event) -> Result<(), Self::Error>;

    /// Get the current version of this aggregate
    fn version(&self) -> i64;
}

/// Repository trait for loading and saving aggregates
///
/// This trait defines the standard operations for persistence
/// of domain aggregates.
#[async_trait]
pub trait Repository<T>: Send + Sync
where
    T: AggregateRoot<Self::Event>,
    Self::Event: DomainEvent,
{
    type Event: DomainEvent;
    type Error: Send + Sync + 'static;

    /// Load an aggregate by its ID
    async fn load(&self, id: &EntityId) -> Result<Option<T>, Self::Error>;

    /// Save an aggregate (persist its uncommitted events)
    async fn save(&self, aggregate: &mut T) -> Result<(), Self::Error>;

    /// Check if an aggregate exists
    async fn exists(&self, id: &EntityId) -> Result<bool, Self::Error>;
}

/// Query handler interface for read-side operations
///
/// Query handlers process read-only queries against
/// materialized views built by projectors.
#[async_trait]
pub trait QueryHandler<Query, Result>: Send + Sync {
    type Error: Send + Sync + 'static;

    /// Handle a query and return the result
    async fn handle(&self, query: Query) -> std::result::Result<Result, Self::Error>;
}

/// Command handler interface for write-side operations
///
/// Command handlers validate business rules and execute
/// commands against domain aggregates.
#[async_trait]
pub trait CommandHandler<Command>: Send + Sync {
    type Error: Send + Sync + 'static;

    /// Handle a command
    async fn handle(&self, command: Command) -> std::result::Result<(), Self::Error>;
}

/// Domain service trait for complex business logic
///
/// Domain services encapsulate business logic that doesn't
/// naturally fit within a single aggregate.
pub trait DomainService: Send + Sync {
    /// Get the name of this domain service
    fn service_name(&self) -> &'static str;
}

/// Value object trait for immutable domain values
///
/// Value objects represent descriptive aspects of the domain
/// with no conceptual identity.
pub trait ValueObject:
    Send + Sync + Clone + PartialEq + Eq + Serialize + for<'de> Deserialize<'de>
{
    /// Validate that this value object is in a valid state
    fn is_valid(&self) -> bool;
}
