//! Domain Aggregate Base Implementation
//! 
//! This module provides a base implementation for domain aggregates
//! following the event sourcing pattern described in the whitepaper.

use atomo_core::{
    traits::{Entity, AggregateRoot},
    events::{DomainEvent, EventEnvelope},
    types::{EntityId, StreamId, Timestamp},
    AtomoError, Result,
};
use async_trait::async_trait;
use std::marker::PhantomData;

/// Base aggregate trait that all domain aggregates should implement
/// 
/// This provides common functionality for event-sourced aggregates
/// including event application, state management, and concurrency control.
pub trait Aggregate<Event>: Entity + Clone
where
    Event: DomainEvent,
{
    /// Apply an event to this aggregate, updating its state
    fn apply(&mut self, event: &Event) -> Result<()>;
    
    /// Get the current version of this aggregate
    fn version(&self) -> i64;
    
    /// Set the version of this aggregate
    fn set_version(&mut self, version: i64);
    
    /// Check if this aggregate is in a valid state
    fn is_valid(&self) -> bool {
        true // Default implementation
    }
}

/// Base aggregate root implementation
/// 
/// This struct provides the common infrastructure needed by all
/// event-sourced aggregates in the Atomo platform.
#[derive(Debug, Clone)]
pub struct AggregateBase<T, Event>
where
    T: Aggregate<Event>,
    Event: DomainEvent,
{
    /// The actual aggregate data
    pub data: T,
    
    /// Current version for optimistic concurrency control
    version: i64,
    
    /// Uncommitted events generated by commands
    uncommitted_events: Vec<Event>,
    
    /// Stream ID for this aggregate
    stream_id: StreamId,
    
    /// Phantom marker for the event type
    _phantom: PhantomData<Event>,
}

impl<T, Event> AggregateBase<T, Event>
where
    T: Aggregate<Event>,
    Event: DomainEvent,
{
    /// Create a new aggregate with initial state
    pub fn new(data: T, stream_id: StreamId) -> Self {
        Self {
            data,
            version: 0,
            uncommitted_events: Vec::new(),
            stream_id,
            _phantom: PhantomData,
        }
    }
    
    /// Create an aggregate from historical events
    pub async fn from_events(
        initial_state: T,
        stream_id: StreamId,
        events: Vec<Event>,
    ) -> Result<Self> {
        let mut aggregate = Self::new(initial_state, stream_id);
        
        for event in events {
            aggregate.apply_event(&event).await?;
        }
        
        // Clear uncommitted events since these are historical
        aggregate.uncommitted_events.clear();
        
        Ok(aggregate)
    }
    
    /// Apply a command that generates events
    pub fn apply_command<C, F>(&mut self, command: C, handler: F) -> Result<()>
    where
        F: FnOnce(&mut T, C) -> Result<Vec<Event>>,
    {
        // Validate current state
        if !self.data.is_valid() {
            return Err(AtomoError::domain("Aggregate is in invalid state"));
        }
        
        // Execute command handler
        let events = handler(&mut self.data, command)?;
        
        // Apply events to update state
        for event in events {
            self.data.apply(&event)?;
            self.version += 1;
            self.data.set_version(self.version);
            self.uncommitted_events.push(event);
        }
        
        Ok(())
    }
    
    /// Get a reference to the aggregate data
    pub fn data(&self) -> &T {
        &self.data
    }
    
    /// Get a mutable reference to the aggregate data
    pub fn data_mut(&mut self) -> &mut T {
        &mut self.data
    }
    
    /// Convert uncommitted events to event envelopes
    pub fn uncommitted_envelopes(&self) -> Vec<EventEnvelope> {
        self.uncommitted_events
            .iter()
            .enumerate()
            .map(|(i, event)| {
                EventEnvelope::from_domain_event(
                    event,
                    self.version - self.uncommitted_events.len() as i64 + i as i64 + 1,
                    0, // Global sequence will be set by event store
                )
            })
            .collect()
    }
}

impl<T, Event> Entity for AggregateBase<T, Event>
where
    T: Aggregate<Event>,
    Event: DomainEvent,
{
    fn id(&self) -> EntityId {
        self.data.id()
    }
    
    fn entity_type(&self) -> &'static str {
        self.data.entity_type()
    }
    
    fn created_at(&self) -> Timestamp {
        self.data.created_at()
    }
    
    fn updated_at(&self) -> Timestamp {
        self.data.updated_at()
    }
}

#[async_trait]
impl<T, Event> AggregateRoot<Event> for AggregateBase<T, Event>
where
    T: Aggregate<Event> + Send + Sync,
    Event: DomainEvent + Send + Sync,
{
    type Error = AtomoError;
    
    fn stream_id(&self) -> StreamId {
        self.stream_id
    }
    
    fn uncommitted_events(&self) -> &[Event] {
        &self.uncommitted_events
    }
    
    fn mark_events_as_committed(&mut self) {
        self.uncommitted_events.clear();
    }
    
    async fn apply_event(&mut self, event: &Event) -> Result<()> {
        self.data.apply(event)?;
        self.version = event.aggregate_version();
        self.data.set_version(self.version);
        Ok(())
    }
    
    fn version(&self) -> i64 {
        self.version
    }
}

/// Repository implementation for aggregates
#[derive(Clone)]
pub struct AggregateRepository<T, Event>
where
    T: Aggregate<Event>,
    Event: DomainEvent,
{
    event_store: std::sync::Arc<dyn atomo_core::events::EventStore<Error = AtomoError> + Send + Sync>,
    _phantom: PhantomData<(T, Event)>,
}

impl<T, Event> AggregateRepository<T, Event>
where
    T: Aggregate<Event>,
    Event: DomainEvent,
{
    pub fn new(
        event_store: std::sync::Arc<dyn atomo_core::events::EventStore<Error = AtomoError> + Send + Sync>,
    ) -> Self {
        Self {
            event_store,
            _phantom: PhantomData,
        }
    }
    
    /// Create a new aggregate with a specific factory function
    pub async fn create_new<F>(&self, factory: F) -> Result<AggregateBase<T, Event>>
    where
        F: FnOnce() -> T,
    {
        let data = factory();
        let stream_id = StreamId::new(); // Generate new stream for new aggregate
        Ok(AggregateBase::new(data, stream_id))
    }
}

#[async_trait]
impl<T, Event> atomo_core::traits::Repository<AggregateBase<T, Event>> for AggregateRepository<T, Event>
where
    T: Aggregate<Event> + Send + Sync + 'static,
    Event: DomainEvent + Send + Sync + 'static + serde::Serialize + for<'de> serde::Deserialize<'de>,
{
    type Event = Event;
    type Error = AtomoError;
    
    async fn load(&self, _id: &EntityId) -> Result<Option<AggregateBase<T, Event>>> {
        // For now, this is a simplified implementation
        // In a real implementation, you would need to:
        // 1. Map entity ID to stream ID (could be same or different)
        // 2. Load events from the stream
        // 3. Replay events to reconstruct aggregate state
        
        // This would require more sophisticated mapping between entity IDs and stream IDs
        todo!("Implement aggregate loading from event store")
    }
    
    async fn save(&self, aggregate: &mut AggregateBase<T, Event>) -> Result<()> {
        if aggregate.uncommitted_events.is_empty() {
            return Ok(());
        }
        
        let envelopes = aggregate.uncommitted_envelopes();
        
        self.event_store
            .append_events(
                aggregate.stream_id(),
                Some(aggregate.version() - envelopes.len() as i64),
                envelopes,
            )
            .await?;
        
        aggregate.mark_events_as_committed();
        
        Ok(())
    }
    
    async fn exists(&self, _id: &EntityId) -> Result<bool> {
        // This would require mapping entity ID to stream ID
        todo!("Implement aggregate existence check")
    }
}
