use anyhow::{Result, Context};
use colored::*;
use console::style;
use std::fs;
use std::path::Path;

pub async fn codegen_command(output_dir: String) -> Result<()> {
    println!("📝 {}", style("Generating client code...").cyan());
    
    println!("   🌐 Introspecting GraphQL schema...");
    
    // Ensure output directory exists
    if !Path::new(&output_dir).exists() {
        fs::create_dir_all(&output_dir)
            .with_context(|| format!("Failed to create output directory: {}", output_dir))?;
    }
    
    println!("   📦 Generating TypeScript types...");
    generate_typescript_types(&output_dir)?;
    
    println!("   🪝 Generating query hooks...");
    generate_query_hooks(&output_dir)?;
    
    println!("   📁 Writing to: {}", output_dir.bright_green());
    
    println!("   ✓ {}", "Client code generation completed!".bright_green());
    
    Ok(())
}

fn generate_typescript_types(output_dir: &str) -> Result<()> {
    let types_content = r#"// Auto-generated TypeScript types for Atomo CRM
// Generated by `atomo codegen` - DO NOT EDIT MANUALLY

export interface Contact {
  id: string;
  streamId: string;
  firstName: string;
  lastName: string;
  email?: string;
  phone?: string;
  companyId?: string;
  title?: string;
  createdAt: string; // ISO date string
  updatedAt: string; // ISO date string
  version: number;
}

export interface Company {
  id: string;
  streamId: string;
  name: string;
  domain?: string;
  website?: string;
  address?: string;
  phone?: string;
  industry?: string;
  employeeCount?: number;
  createdAt: string; // ISO date string
  updatedAt: string; // ISO date string
  version: number;
}

export interface Deal {
  id: string;
  streamId: string;
  title: string;
  description?: string;
  amount?: number;
  currency: string;
  stage: DealStage;
  priority: DealPriority;
  contactId?: string;
  companyId?: string;
  expectedCloseDate?: string; // ISO date string
  actualCloseDate?: string; // ISO date string
  probability: number;
  createdAt: string; // ISO date string
  updatedAt: string; // ISO date string
  version: number;
}

export enum DealStage {
  Lead = 'Lead',
  Qualified = 'Qualified',
  Proposal = 'Proposal',
  Negotiation = 'Negotiation',
  Won = 'Won',
  Lost = 'Lost'
}

export enum DealPriority {
  Low = 'Low',
  Medium = 'Medium',
  High = 'High',
  Critical = 'Critical'
}

// Input types for mutations
export interface CreateContactInput {
  firstName: string;
  lastName: string;
  email?: string;
  phone?: string;
  companyId?: string;
  title?: string;
}

export interface UpdateContactInput {
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
  companyId?: string;
  title?: string;
}

export interface CreateCompanyInput {
  name: string;
  domain?: string;
  website?: string;
  address?: string;
  phone?: string;
  industry?: string;
  employeeCount?: number;
}

export interface UpdateCompanyInput {
  name?: string;
  domain?: string;
  website?: string;
  address?: string;
  phone?: string;
  industry?: string;
  employeeCount?: number;
}

export interface CreateDealInput {
  title: string;
  description?: string;
  amount?: number;
  currency?: string;
  priority?: DealPriority;
  contactId?: string;
  companyId?: string;
  expectedCloseDate?: string; // ISO date string
}

export interface UpdateDealInput {
  title?: string;
  description?: string;
  amount?: number;
  currency?: string;
  stage?: DealStage;
  priority?: DealPriority;
  contactId?: string;
  companyId?: string;
  expectedCloseDate?: string; // ISO date string
  probability?: number;
}
"#;

    let types_file = format!("{}/types.ts", output_dir);
    fs::write(&types_file, types_content)
        .with_context(|| format!("Failed to write types file: {}", types_file))?;
    
    println!("      ✅ Generated: {}", types_file.bright_cyan());
    
    Ok(())
}

fn generate_query_hooks(output_dir: &str) -> Result<()> {
    let hooks_content = r#"// Auto-generated React hooks for Atomo CRM GraphQL API
// Generated by `atomo codegen` - DO NOT EDIT MANUALLY

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { 
  Contact, Company, Deal, 
  CreateContactInput, UpdateContactInput,
  CreateCompanyInput, UpdateCompanyInput,
  CreateDealInput, UpdateDealInput,
  DealStage 
} from './types';

// GraphQL client configuration
const GRAPHQL_ENDPOINT = process.env.NEXT_PUBLIC_GRAPHQL_ENDPOINT || 'http://localhost:8080/graphql';

async function graphqlRequest<T>(query: string, variables?: any): Promise<T> {
  const response = await fetch(GRAPHQL_ENDPOINT, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      query,
      variables,
    }),
  });

  if (!response.ok) {
    throw new Error(`GraphQL request failed: ${response.statusText}`);
  }

  const result = await response.json();
  
  if (result.errors) {
    throw new Error(`GraphQL error: ${result.errors[0].message}`);
  }

  return result.data;
}

// Contact hooks
export function useContacts() {
  return useQuery({
    queryKey: ['contacts'],
    queryFn: () => graphqlRequest<{ contacts: Contact[] }>(`
      query {
        contacts {
          id
          firstName
          lastName
          email
          phone
          companyId
          title
          createdAt
          updatedAt
          version
        }
      }
    `).then(data => data.contacts),
  });
}

export function useContact(id: string) {
  return useQuery({
    queryKey: ['contact', id],
    queryFn: () => graphqlRequest<{ contact: Contact | null }>(`
      query($id: String!) {
        contact(id: $id) {
          id
          firstName
          lastName
          email
          phone
          companyId
          title
          createdAt
          updatedAt
          version
        }
      }
    `, { id }).then(data => data.contact),
    enabled: !!id,
  });
}

export function useCreateContact() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (input: CreateContactInput) => 
      graphqlRequest<{ createContact: Contact }>(`
        mutation($input: CreateContactInput!) {
          createContact(input: $input) {
            id
            firstName
            lastName
            email
            phone
            companyId
            title
            createdAt
            updatedAt
            version
          }
        }
      `, { input }).then(data => data.createContact),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['contacts'] });
    },
  });
}

// Company hooks
export function useCompanies() {
  return useQuery({
    queryKey: ['companies'],
    queryFn: () => graphqlRequest<{ companies: Company[] }>(`
      query {
        companies {
          id
          name
          domain
          website
          address
          phone
          industry
          employeeCount
          createdAt
          updatedAt
          version
        }
      }
    `).then(data => data.companies),
  });
}

export function useCompany(id: string) {
  return useQuery({
    queryKey: ['company', id],
    queryFn: () => graphqlRequest<{ company: Company | null }>(`
      query($id: String!) {
        company(id: $id) {
          id
          name
          domain
          website
          address
          phone
          industry
          employeeCount
          createdAt
          updatedAt
          version
        }
      }
    `, { id }).then(data => data.company),
    enabled: !!id,
  });
}

export function useCreateCompany() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (input: CreateCompanyInput) => 
      graphqlRequest<{ createCompany: Company }>(`
        mutation($input: CreateCompanyInput!) {
          createCompany(input: $input) {
            id
            name
            domain
            website
            address
            phone
            industry
            employeeCount
            createdAt
            updatedAt
            version
          }
        }
      `, { input }).then(data => data.createCompany),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['companies'] });
    },
  });
}

// Deal hooks
export function useDeals() {
  return useQuery({
    queryKey: ['deals'],
    queryFn: () => graphqlRequest<{ deals: Deal[] }>(`
      query {
        deals {
          id
          title
          description
          amount
          currency
          stage
          priority
          contactId
          companyId
          expectedCloseDate
          actualCloseDate
          probability
          createdAt
          updatedAt
          version
        }
      }
    `).then(data => data.deals),
  });
}

export function useDealsByStage(stage: DealStage) {
  return useQuery({
    queryKey: ['deals', 'stage', stage],
    queryFn: () => graphqlRequest<{ dealsByStage: Deal[] }>(`
      query($stage: DealStage!) {
        dealsByStage(stage: $stage) {
          id
          title
          description
          amount
          currency
          stage
          priority
          contactId
          companyId
          expectedCloseDate
          actualCloseDate
          probability
          createdAt
          updatedAt
          version
        }
      }
    `, { stage }).then(data => data.dealsByStage),
  });
}

export function useCreateDeal() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: (input: CreateDealInput) => 
      graphqlRequest<{ createDeal: Deal }>(`
        mutation($input: CreateDealInput!) {
          createDeal(input: $input) {
            id
            title
            description
            amount
            currency
            stage
            priority
            contactId
            companyId
            expectedCloseDate
            actualCloseDate
            probability
            createdAt
            updatedAt
            version
          }
        }
      `, { input }).then(data => data.createDeal),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['deals'] });
    },
  });
}
"#;

    let hooks_file = format!("{}/hooks.ts", output_dir);
    fs::write(&hooks_file, hooks_content)
        .with_context(|| format!("Failed to write hooks file: {}", hooks_file))?;
    
    println!("      ✅ Generated: {}", hooks_file.bright_cyan());
    
    Ok(())
}

fn _generate_package_json(output_dir: &str) -> Result<()> {
    let package_json = r#"{
  "name": "@atomo/client-sdk",
  "version": "0.1.0",
  "description": "Auto-generated TypeScript client SDK for Atomo CRM",
  "main": "index.ts",
  "types": "index.ts",
  "files": [
    "types.ts",
    "hooks.ts",
    "index.ts"
  ],
  "dependencies": {
    "@tanstack/react-query": "^5.0.0"
  },
  "peerDependencies": {
    "react": "^18.0.0"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/atomo-suite/atomo.git",
    "directory": "packages/atomo-client-sdk"
  },
  "license": "MIT"
}
"#;

    let package_file = format!("{}/package.json", output_dir);
    fs::write(&package_file, package_json)
        .with_context(|| format!("Failed to write package.json: {}", package_file))?;
    
    println!("      ✅ Generated: {}", package_file.bright_cyan());
    
    Ok(())
}
